'use strict';

// boats and its child tables. Column format: data-model/README.md
module.exports = [
  {
    table: "boats",
    primaryKey: "id",
    foreignKeys: [],
    columns: [
      { name: "id", type: "text", kind: "pk", source: "boats[].id (record id; generated if absent)" },
      { name: "name", type: "text", kind: "scalar", source: "name" },
      { name: "nameth", type: "text", kind: "scalar", source: "nameTh" },
      { name: "type", type: "text", kind: "scalar", source: "type" },
      { name: "pier", type: "text", kind: "scalar", source: "pier" },
      { name: "cap", type: "bigint", kind: "scalar", source: "cap" },
      { name: "enginecount", type: "bigint", kind: "scalar", source: "engineCount" },
      { name: "use", type: "text", kind: "scalar", source: "use" },
      { name: "material", type: "text", kind: "scalar", source: "material" },
      { name: "reg", type: "text", kind: "scalar", source: "reg" },
      { name: "callsign", type: "text", kind: "scalar", source: "callsign" },
      { name: "imo", type: "text", kind: "scalar", source: "imo" },
      { name: "year", type: "text", kind: "scalar", source: "year" },
      { name: "homeportcity", type: "text", kind: "scalar", source: "homeportCity" },
      { name: "gt", type: "double precision", kind: "scalar", source: "gt" },
      { name: "nt", type: "double precision", kind: "scalar", source: "nt" },
      { name: "dwt", type: "text", kind: "scalar", source: "dwt" },
      { name: "loa", type: "double precision", kind: "scalar", source: "loa" },
      { name: "beam", type: "double precision", kind: "scalar", source: "beam" },
      { name: "depth", type: "double precision", kind: "scalar", source: "depth" },
      { name: "draft", type: "text", kind: "scalar", source: "draft" },
      { name: "lbp", type: "double precision", kind: "scalar", source: "lbp" },
      { name: "bhp", type: "double precision", kind: "scalar", source: "bhp" },
      { name: "licensepax", type: "bigint", kind: "scalar", source: "licensePax" },
      { name: "crew", type: "bigint", kind: "scalar", source: "crew" },
      { name: "fishcrew", type: "text", kind: "scalar", source: "fishcrew" },
      { name: "totalcap", type: "bigint", kind: "scalar", source: "totalcap" },
      { name: "owner", type: "text", kind: "scalar", source: "owner" },
      { name: "homeport", type: "text", kind: "scalar", source: "homeport" },
      { name: "owneraddr", type: "text", kind: "scalar", source: "ownerAddr" },
      { name: "note", type: "text", kind: "scalar", source: "note" },
      { name: "color", type: "text", kind: "scalar", source: "color" },
      { name: "ownership", type: "text", kind: "scalar", source: "ownership" },
      { name: "retired", type: "boolean", kind: "scalar", source: "retired" },
    ],
  },
  {
    table: "boats__docs",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "boats_id", references: "boats.id" }],
    columns: [
      { name: "boats_id", type: "text", kind: "fk", source: "(link) boats.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in docs[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "name", type: "text", kind: "scalar", source: "docs[].name" },
      { name: "exp", type: "text", kind: "scalar", source: "docs[].exp" },
      { name: "renewstatus", type: "text", kind: "scalar", source: "docs[].renewStatus" },
    ],
  },
  {
    table: "boats__log",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "boats_id", references: "boats.id" }],
    columns: [
      { name: "boats_id", type: "text", kind: "fk", source: "(link) boats.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in log[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "id", type: "text", kind: "scalar", source: "log[].id" },
      { name: "s", type: "text", kind: "scalar", source: "log[].s" },
      { name: "from", type: "text", kind: "scalar", source: "log[].from" },
      { name: "to", type: "text", kind: "scalar", source: "log[].to" },
      { name: "loc", type: "text", kind: "scalar", source: "log[].loc" },
      { name: "note", type: "text", kind: "scalar", source: "log[].note" },
      { name: "province", type: "text", kind: "scalar", source: "log[].province" },
      { name: "loctype", type: "text", kind: "scalar", source: "log[].locType" },
      { name: "detail", type: "text", kind: "scalar", source: "log[].detail" },
      { name: "reason", type: "text", kind: "scalar", source: "log[].reason" },
      { name: "projectid", type: "text", kind: "scalar", source: "log[].projectId" },
    ],
  },
  {
    table: "boats__repairhistory",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "boats_id", references: "boats.id" }],
    columns: [
      { name: "boats_id", type: "text", kind: "fk", source: "(link) boats.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in repairHistory[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "date", type: "text", kind: "scalar", source: "repairHistory[].date" },
      { name: "jobno", type: "text", kind: "scalar", source: "repairHistory[].jobNo" },
      { name: "title", type: "text", kind: "scalar", source: "repairHistory[].title" },
      { name: "detail", type: "text", kind: "scalar", source: "repairHistory[].detail" },
      { name: "type", type: "text", kind: "scalar", source: "repairHistory[].type" },
      { name: "location", type: "text", kind: "scalar", source: "repairHistory[].location" },
      { name: "cost", type: "double precision", kind: "scalar", source: "repairHistory[].cost" },
      { name: "startdate", type: "text", kind: "scalar", source: "repairHistory[].startDate" },
      { name: "enddate", type: "text", kind: "scalar", source: "repairHistory[].endDate" },
      { name: "outcome", type: "text", kind: "scalar", source: "repairHistory[].outcome" },
      { name: "closenote", type: "text", kind: "scalar", source: "repairHistory[].closeNote" },
    ],
  },
  {
    table: "boats__repairhistory__assets",
    primaryKey: "row_pk",
    foreignKeys: [],
    columns: [
      { name: "boats_repairhistory_id", type: "text", kind: "fk", source: "(link) boats__repairhistory.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in repairHistory[].assets[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "value", type: "text", kind: "array_scalar", source: "repairHistory[].assets[] (element)" },
    ],
  },
  {
    table: "boats__assignments",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "boats_id", references: "boats.id" }],
    columns: [
      { name: "boats_id", type: "text", kind: "fk", source: "(link) boats.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in assignments[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "id", type: "text", kind: "scalar", source: "assignments[].id" },
      { name: "type", type: "text", kind: "scalar", source: "assignments[].type" },
      { name: "frompier", type: "text", kind: "scalar", source: "assignments[].fromPier" },
      { name: "topier", type: "text", kind: "scalar", source: "assignments[].toPier" },
      { name: "startdate", type: "text", kind: "scalar", source: "assignments[].startDate" },
      { name: "enddate", type: "text", kind: "scalar", source: "assignments[].endDate" },
      { name: "reason", type: "text", kind: "scalar", source: "assignments[].reason" },
      { name: "cost", type: "bigint", kind: "scalar", source: "assignments[].cost" },
      { name: "status", type: "text", kind: "scalar", source: "assignments[].status" },
      { name: "createddate", type: "text", kind: "scalar", source: "assignments[].createdDate" },
    ],
  },
];
