'use strict';

// fleet_maintenance and its child tables. Column format: data-model/README.md
module.exports = [
  {
    table: "fleet_maintenance",
    primaryKey: "id",
    foreignKeys: [],
    columns: [
      { name: "id", type: "text", kind: "pk", source: "fleet_maintenance[].id (record id; generated if absent)" },
      { name: "no", type: "text", kind: "scalar", source: "no" },
      { name: "boatid", type: "text", kind: "scalar", source: "boatId" },
      { name: "type", type: "text", kind: "scalar", source: "type" },
      { name: "title", type: "text", kind: "scalar", source: "title" },
      { name: "detail", type: "text", kind: "scalar", source: "detail" },
      { name: "location", type: "text", kind: "scalar", source: "location" },
      { name: "status", type: "text", kind: "scalar", source: "status" },
      { name: "startdate", type: "text", kind: "scalar", source: "startDate" },
      { name: "enddate", type: "text", kind: "scalar", source: "endDate" },
      { name: "cost", type: "double precision", kind: "scalar", source: "cost" },
      { name: "incidentid", type: "text", kind: "scalar", source: "incidentId" },
      { name: "boatstatus", type: "text", kind: "scalar", source: "boatStatus" },
      { name: "boatstatusreason", type: "text", kind: "scalar", source: "boatStatusReason" },
      { name: "setfixing", type: "boolean", kind: "scalar", source: "setFixing" },
      { name: "outcome", type: "text", kind: "scalar", source: "outcome" },
      { name: "parentprojectid", type: "text", kind: "scalar", source: "parentProjectId" },
      { name: "awaitinginvoice", type: "boolean", kind: "scalar", source: "awaitingInvoice" },
      { name: "closenote", type: "text", kind: "scalar", source: "closeNote" },
    ],
  },
  {
    table: "fleet_maintenance__assets",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "fleet_maintenance_id", references: "fleet_maintenance.id" }],
    columns: [
      { name: "fleet_maintenance_id", type: "text", kind: "fk", source: "(link) fleet_maintenance.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in assets[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "type", type: "text", kind: "scalar", source: "assets[].type" },
      { name: "engid", type: "text", kind: "scalar", source: "assets[].engId" },
      { name: "label", type: "text", kind: "scalar", source: "assets[].label" },
      { name: "detail", type: "text", kind: "scalar", source: "assets[].detail" },
      { name: "status", type: "text", kind: "scalar", source: "assets[].status" },
      { name: "gbid", type: "text", kind: "scalar", source: "assets[].gbId" },
      { name: "propid", type: "text", kind: "scalar", source: "assets[].propId" },
      { name: "id", type: "text", kind: "scalar", source: "assets[].id" },
    ],
  },
  {
    table: "fleet_maintenance__progresslog",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "fleet_maintenance_id", references: "fleet_maintenance.id" }],
    columns: [
      { name: "fleet_maintenance_id", type: "text", kind: "fk", source: "(link) fleet_maintenance.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in progressLog[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "date", type: "text", kind: "scalar", source: "progressLog[].date" },
      { name: "text", type: "text", kind: "scalar", source: "progressLog[].text" },
      { name: "by", type: "text", kind: "scalar", source: "progressLog[].by" },
      { name: "createdat", type: "text", kind: "scalar", source: "progressLog[].createdAt" },
    ],
  },
  {
    table: "fleet_maintenance__parts",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "fleet_maintenance_id", references: "fleet_maintenance.id" }],
    columns: [
      { name: "fleet_maintenance_id", type: "text", kind: "fk", source: "(link) fleet_maintenance.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in parts[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "invid", type: "text", kind: "scalar", source: "parts[].invId" },
      { name: "name", type: "text", kind: "scalar", source: "parts[].name" },
      { name: "qty", type: "bigint", kind: "scalar", source: "parts[].qty" },
      { name: "unit", type: "text", kind: "scalar", source: "parts[].unit" },
      { name: "cost", type: "double precision", kind: "scalar", source: "parts[].cost" },
      { name: "location", type: "text", kind: "scalar", source: "parts[].location" },
      { name: "date", type: "text", kind: "scalar", source: "parts[].date" },
    ],
  },
];
