'use strict';

// fleet_memos and its child tables. Column format: data-model/README.md
module.exports = [
  {
    table: "fleet_memos",
    primaryKey: "id",
    foreignKeys: [],
    columns: [
      { name: "id", type: "text", kind: "pk", source: "fleet_memos[].id (record id; generated if absent)" },
      { name: "no", type: "text", kind: "scalar", source: "no" },
      { name: "title", type: "text", kind: "scalar", source: "title" },
      { name: "boatid", type: "text", kind: "scalar", source: "boatId" },
      { name: "memotype", type: "text", kind: "scalar", source: "memoType" },
      { name: "proposer", type: "text", kind: "scalar", source: "proposer" },
      { name: "from", type: "text", kind: "scalar", source: "from" },
      { name: "to", type: "text", kind: "scalar", source: "to" },
      { name: "cc", type: "text", kind: "scalar", source: "cc" },
      { name: "createddate", type: "text", kind: "scalar", source: "createdDate" },
      { name: "status", type: "text", kind: "scalar", source: "status" },
      { name: "currentstep", type: "bigint", kind: "scalar", source: "currentStep" },
      { name: "vatenabled", type: "boolean", kind: "scalar", source: "vatEnabled" },
      { name: "vatrate", type: "bigint", kind: "scalar", source: "vatRate" },
      { name: "refnote", type: "text", kind: "scalar", source: "refNote" },
      { name: "subtotal", type: "double precision", kind: "scalar", source: "subtotal" },
      { name: "discount", type: "double precision", kind: "scalar", source: "discount" },
      { name: "vat", type: "double precision", kind: "scalar", source: "vat" },
      { name: "amount", type: "double precision", kind: "scalar", source: "amount" },
      { name: "approvedby", type: "text", kind: "scalar", source: "approvedBy" },
      { name: "approveddate", type: "text", kind: "scalar", source: "approvedDate" },
      { name: "approvenote", type: "text", kind: "scalar", source: "approveNote" },
      { name: "ordereddate", type: "text", kind: "scalar", source: "orderedDate" },
      { name: "receiveddate", type: "text", kind: "scalar", source: "receivedDate" },
      { name: "supplier", type: "text", kind: "scalar", source: "supplier" },
      { name: "discountpct", type: "bigint", kind: "scalar", source: "discountPct" },
      { name: "maintid", type: "text", kind: "scalar", source: "maintId" },
      { name: "scope", type: "text", kind: "scalar", source: "scope" },
      { name: "generalcategory", type: "text", kind: "scalar", source: "generalCategory" },
      { name: "note", type: "text", kind: "scalar", source: "note" },
      { name: "orderedby", type: "text", kind: "scalar", source: "orderedBy" },
      { name: "receivedby", type: "text", kind: "scalar", source: "receivedBy" },
      { name: "paiddate", type: "text", kind: "scalar", source: "paidDate" },
      { name: "paidby", type: "text", kind: "scalar", source: "paidBy" },
      { name: "paidvia", type: "text", kind: "scalar", source: "paidVia" },
      { name: "discountamt", type: "bigint", kind: "scalar", source: "discountAmt" },
      { name: "afterdiscount", type: "double precision", kind: "scalar", source: "afterDiscount" },
      { name: "receivedlocation", type: "text", kind: "scalar", source: "receivedLocation" },
      { name: "receivedsummary", type: "text", kind: "scalar", source: "receivedSummary" },
      { name: "projectid", type: "text", kind: "scalar", source: "projectId" },
    ],
  },
  {
    table: "fleet_memos__items",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "fleet_memos_id", references: "fleet_memos.id" }],
    columns: [
      { name: "fleet_memos_id", type: "text", kind: "fk", source: "(link) fleet_memos.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in items[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "name", type: "text", kind: "scalar", source: "items[].name" },
      { name: "qty", type: "double precision", kind: "scalar", source: "items[].qty" },
      { name: "price", type: "double precision", kind: "scalar", source: "items[].price" },
      { name: "category", type: "text", kind: "scalar", source: "items[].category" },
      { name: "partno", type: "text", kind: "scalar", source: "items[].partNo" },
      { name: "invid", type: "text", kind: "scalar", source: "items[].invId" },
      { name: "unit", type: "text", kind: "scalar", source: "items[].unit" },
      { name: "frominventory", type: "boolean", kind: "scalar", source: "items[].fromInventory" },
      { name: "discountpct", type: "double precision", kind: "scalar", source: "items[].discountPct" },
      { name: "autoregister", type: "boolean", kind: "scalar", source: "items[].autoRegister" },
      { name: "inventorysnapshot_cost", type: "double precision", kind: "scalar", source: "items[].inventorySnapshot.cost" },
      { name: "inventorysnapshot_primarylocation", type: "text", kind: "scalar", source: "items[].inventorySnapshot.primaryLocation" },
      { name: "inventorysnapshot_qtyatselection", type: "double precision", kind: "scalar", source: "items[].inventorySnapshot.qtyAtSelection" },
    ],
  },
];
