'use strict';

// fleet_gearboxes and its child tables. Column format: data-model/README.md
module.exports = [
  {
    table: "fleet_gearboxes",
    primaryKey: "id",
    foreignKeys: [],
    columns: [
      { name: "id", type: "text", kind: "pk", source: "fleet_gearboxes[].id (record id; generated if absent)" },
      { name: "boatid", type: "text", kind: "scalar", source: "boatId" },
      { name: "engineid", type: "text", kind: "scalar", source: "engineId" },
      { name: "brand", type: "text", kind: "scalar", source: "brand" },
      { name: "model", type: "text", kind: "scalar", source: "model" },
      { name: "serial", type: "text", kind: "scalar", source: "serial" },
      { name: "status", type: "text", kind: "scalar", source: "status" },
      { name: "basehours", type: "bigint", kind: "scalar", source: "baseHours" },
      { name: "buydate", type: "text", kind: "scalar", source: "buyDate" },
      { name: "note", type: "text", kind: "scalar", source: "note" },
      { name: "sparelocation", type: "text", kind: "scalar", source: "spareLocation" },
      { name: "shaftlength", type: "text", kind: "scalar", source: "shaftLength" },
      { name: "modelsuffix", type: "text", kind: "scalar", source: "modelSuffix" },
      { name: "installhours", type: "double precision", kind: "scalar", source: "installHours" },
      { name: "rotation", type: "text", kind: "scalar", source: "rotation" },
      { name: "gearratio", type: "text", kind: "scalar", source: "gearRatio" },
      { name: "oilcapacity", type: "text", kind: "scalar", source: "oilCapacity" },
      { name: "serviceinterval", type: "bigint", kind: "scalar", source: "serviceInterval" },
      { name: "lastservicedate", type: "text", kind: "scalar", source: "lastServiceDate" },
      { name: "onboatid", type: "text", kind: "scalar", source: "onBoatId" },
      { name: "onboatpos", type: "text", kind: "scalar", source: "onBoatPos" },
    ],
  },
  {
    table: "fleet_gearboxes__log",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "fleet_gearboxes_id", references: "fleet_gearboxes.id" }],
    columns: [
      { name: "fleet_gearboxes_id", type: "text", kind: "fk", source: "(link) fleet_gearboxes.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in log[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "date", type: "text", kind: "scalar", source: "log[].date" },
      { name: "type", type: "text", kind: "scalar", source: "log[].type" },
      { name: "desc", type: "text", kind: "scalar", source: "log[].desc" },
      { name: "enginehours", type: "double precision", kind: "scalar", source: "log[].engineHours" },
      { name: "fromloc", type: "text", kind: "scalar", source: "log[].fromLoc" },
      { name: "toloc", type: "text", kind: "scalar", source: "log[].toLoc" },
      { name: "usedhours", type: "bigint", kind: "scalar", source: "log[].usedHours" },
      { name: "incidentid", type: "text", kind: "scalar", source: "log[].incidentId" },
      { name: "outcome", type: "text", kind: "scalar", source: "log[].outcome" },
      { name: "detail", type: "text", kind: "scalar", source: "log[].detail" },
      { name: "text", type: "text", kind: "scalar", source: "log[].text" },
    ],
  },
];
