'use strict';

// sb_agents and its child tables. Column format: data-model/README.md
module.exports = [
  {
    table: "sb_agents",
    primaryKey: "id",
    foreignKeys: [],
    columns: [
      { name: "id", type: "text", kind: "pk", source: "sb_agents[].id (record id; generated if absent)" },
      { name: "code", type: "text", kind: "scalar", source: "code" },
      { name: "name", type: "text", kind: "scalar", source: "name" },
      { name: "market", type: "text", kind: "scalar", source: "market" },
      { name: "sub", type: "text", kind: "scalar", source: "sub" },
      { name: "sales", type: "text", kind: "scalar", source: "sales" },
      { name: "paytype", type: "text", kind: "scalar", source: "payType" },
      { name: "vatmode", type: "text", kind: "scalar", source: "vatMode" },
      { name: "creditdays", type: "bigint", kind: "scalar", source: "creditDays" },
      { name: "creditlimit", type: "bigint", kind: "scalar", source: "creditLimit" },
      { name: "creditbalance", type: "bigint", kind: "scalar", source: "creditBalance" },
      { name: "contact", type: "text", kind: "scalar", source: "contact" },
      { name: "email", type: "text", kind: "scalar", source: "email" },
      { name: "phone", type: "text", kind: "scalar", source: "phone" },
      { name: "note", type: "text", kind: "scalar", source: "note" },
      { name: "contractstatus", type: "text", kind: "scalar", source: "contractStatus" },
      { name: "contractversion", type: "text", kind: "scalar", source: "contractVersion" },
      { name: "companyinfo_legalname", type: "text", kind: "scalar", source: "companyInfo.legalName" },
      { name: "companyinfo_tatlicense", type: "text", kind: "scalar", source: "companyInfo.tatLicense" },
      { name: "companyinfo_address", type: "text", kind: "scalar", source: "companyInfo.address" },
      { name: "companyinfo_tel", type: "text", kind: "scalar", source: "companyInfo.tel" },
      { name: "companyinfo_hotline", type: "text", kind: "scalar", source: "companyInfo.hotline" },
      { name: "companyinfo_fax", type: "text", kind: "scalar", source: "companyInfo.fax" },
      { name: "companyinfo_website", type: "text", kind: "scalar", source: "companyInfo.website" },
      { name: "agentsignatory_name", type: "text", kind: "scalar", source: "agentSignatory.name" },
      { name: "agentsignatory_designation", type: "text", kind: "scalar", source: "agentSignatory.designation" },
      { name: "agentsignatory_tel", type: "text", kind: "scalar", source: "agentSignatory.tel" },
      { name: "agentsignatory_signeddate", type: "text", kind: "scalar", source: "agentSignatory.signedDate" },
      { name: "bookingchannel_method", type: "text", kind: "scalar", source: "bookingChannel.method" },
      { name: "bookingchannel_cutoff", type: "text", kind: "scalar", source: "bookingChannel.cutoff" },
      { name: "bookingchannel_cancelpolicy", type: "text", kind: "scalar", source: "bookingChannel.cancelPolicy" },
      { name: "bookingchannel_email", type: "text", kind: "scalar", source: "bookingChannel.email" },
      { name: "bookingchannel_phone", type: "text", kind: "scalar", source: "bookingChannel.phone" },
      { name: "contractstart", type: "text", kind: "scalar", source: "contractStart" },
      { name: "contractend", type: "text", kind: "scalar", source: "contractEnd" },
      { name: "ratetypeid", type: "text", kind: "scalar", source: "rateTypeId" },
      { name: "color", type: "text", kind: "scalar", source: "color" },
      { name: "companyinfo_taxid", type: "text", kind: "scalar", source: "companyInfo.taxId" },
      { name: "contracttemplateid", type: "text", kind: "scalar", source: "contractTemplateId", note: "which contract template this agent's contract is generated from · empty = the default template" },
    ],
  },
  {
    table: "sb_agents__programs",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_agents_id", references: "sb_agents.id" }],
    columns: [
      { name: "sb_agents_id", type: "text", kind: "fk", source: "(link) sb_agents.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in programs[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "value", type: "text", kind: "array_scalar", source: "programs[] (element)" },
    ],
  },
  {
    table: "sb_agents__programperiods",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_agents_id", references: "sb_agents.id" }],
    columns: [
      { name: "sb_agents_id", type: "text", kind: "fk", source: "(link) sb_agents.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in programPeriods[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "routeid", type: "text", kind: "scalar", source: "programPeriods[].routeId" },
      { name: "bookfrom", type: "text", kind: "scalar", source: "programPeriods[].bookFrom" },
      { name: "bookto", type: "text", kind: "scalar", source: "programPeriods[].bookTo" },
      { name: "travelfrom", type: "text", kind: "scalar", source: "programPeriods[].travelFrom" },
      { name: "travelto", type: "text", kind: "scalar", source: "programPeriods[].travelTo" },
      { name: "note", type: "text", kind: "scalar", source: "programPeriods[].note" },
    ],
  },
  {
    table: "sb_agents__activity",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_agents_id", references: "sb_agents.id" }],
    columns: [
      { name: "sb_agents_id", type: "text", kind: "fk", source: "(link) sb_agents.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in activity[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "at", type: "text", kind: "scalar", source: "activity[].at" },
      { name: "by", type: "text", kind: "scalar", source: "activity[].by" },
      { name: "kind", type: "text", kind: "scalar", source: "activity[].kind" },
      { name: "text", type: "text", kind: "scalar", source: "activity[].text" },
    ],
  },
  {
    table: "sb_agents__contracthistory",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_agents_id", references: "sb_agents.id" }],
    columns: [
      { name: "sb_agents_id", type: "text", kind: "fk", source: "(link) sb_agents.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in contractHistory[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "version", type: "text", kind: "scalar", source: "contractHistory[].version" },
      { name: "archivedat", type: "text", kind: "scalar", source: "contractHistory[].archivedAt" },
      { name: "contractstart", type: "text", kind: "scalar", source: "contractHistory[].contractStart" },
      { name: "contractend", type: "text", kind: "scalar", source: "contractHistory[].contractEnd" },
      { name: "snapshot_agentsignatory_name", type: "text", kind: "scalar", source: "contractHistory[].snapshot.agentSignatory.name" },
      { name: "snapshot_agentsignatory_designation", type: "text", kind: "scalar", source: "contractHistory[].snapshot.agentSignatory.designation" },
      { name: "snapshot_agentsignatory_tel", type: "text", kind: "scalar", source: "contractHistory[].snapshot.agentSignatory.tel" },
      { name: "snapshot_agentsignatory_signeddate", type: "text", kind: "scalar", source: "contractHistory[].snapshot.agentSignatory.signedDate" },
      { name: "snapshot_programperiods", type: "text", kind: "json_text", source: "contractHistory[].snapshot.programPeriods" },
      { name: "snapshot_addonservices", type: "text", kind: "json_text", source: "contractHistory[].snapshot.addonServices" },
      { name: "snapshot_prices", type: "text", kind: "json_text", source: "contractHistory[].snapshot.prices" },
    ],
  },
];
