'use strict';

// sb_bookings and its child tables. Column format: data-model/README.md
module.exports = [
  {
    table: "sb_bookings",
    primaryKey: "id",
    foreignKeys: [],
    columns: [
      { name: "id", type: "text", kind: "pk", source: "sb_bookings[].id (record id; generated if absent)" },
      { name: "schemaver", type: "bigint", kind: "scalar", source: "schemaVer" },
      { name: "createdat", type: "text", kind: "scalar", source: "createdAt" },
      { name: "createdby", type: "text", kind: "scalar", source: "createdBy" },
      { name: "voucherref", type: "text", kind: "scalar", source: "voucherRef" },
      { name: "agentid", type: "text", kind: "scalar", source: "agentId" },
      { name: "ratetyperef", type: "text", kind: "scalar", source: "rateTypeRef" },
      { name: "leadpax", type: "text", kind: "scalar", source: "leadPax" },
      { name: "leadnationality", type: "text", kind: "scalar", source: "leadNationality" },
      { name: "leadtype", type: "text", kind: "scalar", source: "leadType" },
      { name: "leadfoc", type: "boolean", kind: "scalar", source: "leadFoc" },
      { name: "leadphone", type: "text", kind: "scalar", source: "leadPhone" },
      { name: "leademail", type: "text", kind: "scalar", source: "leadEmail" },
      { name: "pickupareaid", type: "text", kind: "scalar", source: "pickupAreaId" },
      { name: "pickupself", type: "boolean", kind: "scalar", source: "pickupSelf" },
      { name: "pickuparea", type: "text", kind: "scalar", source: "pickupArea" },
      { name: "pickupzone", type: "text", kind: "scalar", source: "pickupZone" },
      { name: "hotelname", type: "text", kind: "scalar", source: "hotelName" },
      { name: "roomnumber", type: "text", kind: "scalar", source: "roomNumber" },
      { name: "dropoffsame", type: "boolean", kind: "scalar", source: "dropoffSame" },
      { name: "dropoffareaid", type: "text", kind: "scalar", source: "dropoffAreaId" },
      { name: "dropoffarea", type: "text", kind: "scalar", source: "dropoffArea" },
      { name: "dropoffhotelname", type: "text", kind: "scalar", source: "dropoffHotelName" },
      { name: "guides_english", type: "boolean", kind: "scalar", source: "guides.english" },
      { name: "guides_russian", type: "boolean", kind: "scalar", source: "guides.russian" },
      { name: "guides_chinese", type: "boolean", kind: "scalar", source: "guides.chinese" },
      { name: "guides_otherlang", type: "text", kind: "scalar", source: "guides.otherLang" },
      { name: "notes", type: "text", kind: "scalar", source: "notes" },
      { name: "specialmeals_veg", type: "bigint", kind: "scalar", source: "specialMeals.veg" },
      { name: "specialmeals_vegan", type: "bigint", kind: "scalar", source: "specialMeals.vegan" },
      { name: "specialmeals_halal", type: "bigint", kind: "scalar", source: "specialMeals.halal" },
      { name: "specialmeals_allergies", type: "text", kind: "scalar", source: "specialMeals.allergies" },
      { name: "largeluggage", type: "bigint", kind: "scalar", source: "largeLuggage" },
      { name: "cashontour", type: "text", kind: "scalar", source: "cashOnTour" },
      { name: "focapproval", type: "text", kind: "scalar", source: "focApproval" },
      { name: "paymentsnapshot_method", type: "text", kind: "scalar", source: "paymentSnapshot.method" },
      { name: "paymentsnapshot_netdays", type: "bigint", kind: "scalar", source: "paymentSnapshot.netDays" },
      { name: "paymentsnapshot_source", type: "text", kind: "scalar", source: "paymentSnapshot.source" },
      { name: "paymentsnapshot_contractversion", type: "text", kind: "scalar", source: "paymentSnapshot.contractVersion" },
      { name: "paymentsnapshot_paid", type: "bigint", kind: "scalar", source: "paymentSnapshot.paid" },
      { name: "paymentsnapshot_paidstatus", type: "text", kind: "scalar", source: "paymentSnapshot.paidStatus" },
      { name: "paymentsnapshot_deposit", type: "bigint", kind: "scalar", source: "paymentSnapshot.deposit" },
      { name: "paymentsnapshot_balance", type: "bigint", kind: "scalar", source: "paymentSnapshot.balance" },
      { name: "pricebreakdown_seat", type: "bigint", kind: "scalar", source: "priceBreakdown.seat" },
      { name: "pricebreakdown_addon", type: "bigint", kind: "scalar", source: "priceBreakdown.addOn" },
      { name: "pricebreakdown_focdiscount", type: "bigint", kind: "scalar", source: "priceBreakdown.focDiscount" },
      { name: "pricebreakdown_discount", type: "bigint", kind: "scalar", source: "priceBreakdown.discount" },
      { name: "pricebreakdown_extra", type: "bigint", kind: "scalar", source: "priceBreakdown.extra" },
      { name: "pricebreakdown_total", type: "bigint", kind: "scalar", source: "priceBreakdown.total" },
      { name: "status", type: "text", kind: "scalar", source: "status" },
      { name: "total", type: "bigint", kind: "scalar", source: "total" },
      { name: "soldby", type: "text", kind: "scalar", source: "soldBy" },
      { name: "pricemode", type: "text", kind: "scalar", source: "priceMode" },
      { name: "manualtotal", type: "bigint", kind: "scalar", source: "manualTotal" },
      { name: "purpose", type: "text", kind: "scalar", source: "purpose" },
      { name: "staffid", type: "text", kind: "scalar", source: "staffId" },
      { name: "staffpurpose", type: "text", kind: "scalar", source: "staffPurpose" },
      { name: "note", type: "text", kind: "scalar", source: "note" },
      { name: "bookedat", type: "text", kind: "scalar", source: "bookedAt" },
      { name: "bookingdate", type: "text", kind: "scalar", source: "bookingDate" },
      { name: "marketsnapshot_market", type: "text", kind: "scalar", source: "marketSnapshot.market" },
      { name: "marketsnapshot_sub", type: "text", kind: "scalar", source: "marketSnapshot.sub" },
      { name: "marketsnapshot_agentid", type: "text", kind: "scalar", source: "marketSnapshot.agentId" },
      { name: "marketsnapshot_at", type: "text", kind: "scalar", source: "marketSnapshot.at" },
      { name: "confirmedby", type: "text", kind: "scalar", source: "confirmedBy" },
      { name: "confirmedat", type: "text", kind: "scalar", source: "confirmedAt" },
      { name: "ops_boatid", type: "text", kind: "scalar", source: "ops.boatId" },
      { name: "updatedat", type: "text", kind: "scalar", source: "updatedAt" },
      { name: "updatedby", type: "text", kind: "scalar", source: "updatedBy" },
      { name: "focapproval_count", type: "bigint", kind: "scalar", source: "focApproval.count" },
      { name: "focapproval_reason", type: "text", kind: "scalar", source: "focApproval.reason" },
      { name: "focapproval_status", type: "text", kind: "scalar", source: "focApproval.status" },
      { name: "focapproval_requestedat", type: "text", kind: "scalar", source: "focApproval.requestedAt" },
      { name: "focapproval_requestedby", type: "text", kind: "scalar", source: "focApproval.requestedBy" },
      { name: "focapproval_approvedat", type: "text", kind: "scalar", source: "focApproval.approvedAt" },
      { name: "focapproval_approvedby", type: "text", kind: "scalar", source: "focApproval.approvedBy" },
      { name: "focreason", type: "text", kind: "scalar", source: "focReason" },
      { name: "ops_vangroup", type: "bigint", kind: "scalar", source: "ops.vanGroup" },
      { name: "ops_vanseq", type: "bigint", kind: "scalar", source: "ops.vanSeq" },
      { name: "ops_vanreturnid", type: "text", kind: "scalar", source: "ops.vanReturnId" },
      { name: "ops_vanid", type: "text", kind: "scalar", source: "ops.vanId" },
      { name: "invoiceid", type: "text", kind: "scalar", source: "invoiceId" },
      { name: "paymentstatus", type: "text", kind: "scalar", source: "paymentStatus" },
      { name: "ops_returnsamevan", type: "boolean", kind: "scalar", source: "ops.returnSameVan" },
      { name: "cashontour_amount", type: "bigint", kind: "scalar", source: "cashOnTour.amount" },
      { name: "cashontour_currency", type: "text", kind: "scalar", source: "cashOnTour.currency" },
      { name: "cashontour_handling", type: "text", kind: "scalar", source: "cashOnTour.handling" },
      { name: "cashontour_note", type: "text", kind: "scalar", source: "cashOnTour.note" },
      { name: "cancelledat", type: "text", kind: "scalar", source: "cancelledAt" },
      { name: "cancellation_category", type: "text", kind: "scalar", source: "cancellation.category" },
      { name: "cancellation_categorylabel", type: "text", kind: "scalar", source: "cancellation.categoryLabel" },
      { name: "cancellation_group", type: "text", kind: "scalar", source: "cancellation.group" },
      { name: "cancellation_note", type: "text", kind: "scalar", source: "cancellation.note" },
      { name: "cancellation_reason", type: "text", kind: "scalar", source: "cancellation.reason" },
      { name: "cancellation_chargetype", type: "text", kind: "scalar", source: "cancellation.chargeType" },
      { name: "cancellation_chargeamount", type: "bigint", kind: "scalar", source: "cancellation.chargeAmount" },
      { name: "cancellation_at", type: "text", kind: "scalar", source: "cancellation.at" },
      { name: "cancellation_by", type: "text", kind: "scalar", source: "cancellation.by" },
      { name: "cancelcategory", type: "text", kind: "scalar", source: "cancelCategory" },
      { name: "cancelreason", type: "text", kind: "scalar", source: "cancelReason" },
      { name: "reschedule_fromdate", type: "text", kind: "scalar", source: "reschedule.fromDate" },
      { name: "reschedule_todate", type: "text", kind: "scalar", source: "reschedule.toDate" },
      { name: "reschedule_reason", type: "text", kind: "scalar", source: "reschedule.reason" },
      { name: "reschedule_chargetype", type: "text", kind: "scalar", source: "reschedule.chargeType" },
      { name: "reschedule_chargeamount", type: "bigint", kind: "scalar", source: "reschedule.chargeAmount" },
      { name: "reschedule_collect", type: "text", kind: "scalar", source: "reschedule.collect" },
      { name: "reschedule_at", type: "text", kind: "scalar", source: "reschedule.at" },
      { name: "reschedule_by", type: "text", kind: "scalar", source: "reschedule.by" },
      { name: "rebook_from", type: "text", kind: "scalar", source: "rebook.from" },
      { name: "rebook_to", type: "text", kind: "scalar", source: "rebook.to" },
      { name: "rebook_reason", type: "text", kind: "scalar", source: "rebook.reason" },
      { name: "rebook_at", type: "text", kind: "scalar", source: "rebook.at" },
      { name: "ops_pickuptimefinal", type: "text", kind: "scalar", source: "ops.pickupTimeFinal" },
      { name: "approval_status", type: "text", kind: "scalar", source: "approval.status" },
      { name: "approval_reason", type: "text", kind: "scalar", source: "approval.reason" },
      { name: "approval_targetstatus", type: "text", kind: "scalar", source: "approval.targetStatus" },
      { name: "approval_totover", type: "bigint", kind: "scalar", source: "approval.totOver" },
      { name: "approval_requestedby", type: "text", kind: "scalar", source: "approval.requestedBy" },
      { name: "approval_requestedat", type: "text", kind: "scalar", source: "approval.requestedAt" },
      { name: "approval_approvedby", type: "text", kind: "scalar", source: "approval.approvedBy" },
      { name: "approval_approvedat", type: "text", kind: "scalar", source: "approval.approvedAt" },
      { name: "approval_note", type: "text", kind: "scalar", source: "approval.note" },
      { name: "ops_reconfirm", type: "text", kind: "json_text", source: "ops.reconfirm" },
      { name: "weatherresolve_event", type: "text", kind: "scalar", source: "weatherResolve.event" },
      { name: "weatherresolve_status", type: "text", kind: "scalar", source: "weatherResolve.status" },
      { name: "weatherresolve_notifiedat", type: "text", kind: "scalar", source: "weatherResolve.notifiedAt" },
      { name: "weatherresolve_outcome", type: "text", kind: "scalar", source: "weatherResolve.outcome" },
      { name: "weatherresolve_resolvedat", type: "text", kind: "scalar", source: "weatherResolve.resolvedAt" },
      { name: "weatherresolve_newdate", type: "text", kind: "scalar", source: "weatherResolve.newDate" },
      { name: "editlock_uid", type: "text", kind: "scalar", source: "editLock.uid" },
      { name: "editlock_by", type: "text", kind: "scalar", source: "editLock.by" },
      { name: "editlock_at", type: "bigint", kind: "scalar", source: "editLock.at" },
      { name: "doccheck", type: "text", kind: "json_text", source: "docCheck" },
      { name: "attachments", type: "text", kind: "json_text", source: "attachments" },
      { name: "paymentslips", type: "text", kind: "json_text", source: "paymentSlips" },
      { name: "incomplete", type: "text", kind: "json_text", source: "incomplete" },
      { name: "approval_over", type: "text", kind: "json_text", source: "approval.over" },
      { name: "altpickups", type: "text", kind: "json_text", source: "altPickups" },
      { name: "ops_vansplits", type: "text", kind: "json_text", source: "ops.vanSplits" },
      { name: "ops_boatsplits", type: "text", kind: "json_text", source: "ops.boatSplits" },
      { name: "ops_vancheckin", type: "text", kind: "json_text", source: "ops.vanCheckin" },
      { name: "ops_piercheckin", type: "text", kind: "json_text", source: "ops.pierCheckin" },
      { name: "ops_piernote", type: "text", kind: "json_text", source: "ops.pierNote" },
      { name: "pierpayments", type: "text", kind: "json_text", source: "pierPayments" },
      { name: "b2coverride", type: "text", kind: "json_text", source: "b2cOverride" },
      { name: "specialmeals_allergylist", type: "text", kind: "json_text", source: "specialMeals.allergyList" },
    ],
  },
  {
    table: "sb_bookings__passengers",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_bookings_id", references: "sb_bookings.id" }],
    columns: [
      { name: "sb_bookings_id", type: "text", kind: "fk", source: "(link) sb_bookings.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in passengers[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "name", type: "text", kind: "scalar", source: "passengers[].name" },
      { name: "nationality", type: "text", kind: "scalar", source: "passengers[].nationality" },
      { name: "type", type: "text", kind: "scalar", source: "passengers[].type" },
      { name: "foc", type: "boolean", kind: "scalar", source: "passengers[].foc" },
    ],
  },
  {
    table: "sb_bookings__trips",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_bookings_id", references: "sb_bookings.id" }],
    columns: [
      { name: "sb_bookings_id", type: "text", kind: "fk", source: "(link) sb_bookings.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in trips[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "routeid", type: "text", kind: "scalar", source: "trips[].routeId" },
      { name: "date", type: "text", kind: "scalar", source: "trips[].date" },
      { name: "zone", type: "text", kind: "scalar", source: "trips[].zone" },
      { name: "pax_ad_fr", type: "bigint", kind: "scalar", source: "trips[].pax.ad_fr" },
      { name: "pax_chd_fr", type: "bigint", kind: "scalar", source: "trips[].pax.chd_fr" },
      { name: "pax_inf_fr", type: "bigint", kind: "scalar", source: "trips[].pax.inf_fr" },
      { name: "pax_foc_fr", type: "bigint", kind: "scalar", source: "trips[].pax.foc_fr" },
      { name: "pax_ad_th", type: "bigint", kind: "scalar", source: "trips[].pax.ad_th" },
      { name: "pax_chd_th", type: "bigint", kind: "scalar", source: "trips[].pax.chd_th" },
      { name: "pax_inf_th", type: "bigint", kind: "scalar", source: "trips[].pax.inf_th" },
      { name: "pax_foc_th", type: "bigint", kind: "scalar", source: "trips[].pax.foc_th" },
      { name: "pax_ad", type: "bigint", kind: "scalar", source: "trips[].pax.ad" },
      { name: "pickuptime", type: "text", kind: "scalar", source: "trips[].pickupTime" },
      { name: "bookingmode", type: "text", kind: "scalar", source: "trips[].bookingMode" },
      { name: "charterboatid", type: "text", kind: "scalar", source: "trips[].charterBoatId" },
      { name: "charterpricemode", type: "text", kind: "scalar", source: "trips[].charterPriceMode" },
      { name: "charterpricemanual", type: "bigint", kind: "scalar", source: "trips[].charterPriceManual" },
      { name: "charterpricenote", type: "text", kind: "scalar", source: "trips[].charterPriceNote" },
      { name: "charterdisplacementack", type: "boolean", kind: "scalar", source: "trips[].charterDisplacementAck" },
      { name: "ovn", type: "text", kind: "scalar", source: "trips[].ovn" },
      { name: "ovnreturndate", type: "text", kind: "scalar", source: "trips[].ovnReturnDate" },
      { name: "ovncharge", type: "bigint", kind: "scalar", source: "trips[].ovnCharge" },
      { name: "ovnleg", type: "boolean", kind: "scalar", source: "trips[].ovnLeg" },
      { name: "ovnof", type: "text", kind: "scalar", source: "trips[].ovnOf" },
      { name: "seatsource_locked", type: "bigint", kind: "scalar", source: "trips[].seatSource.locked" },
      { name: "seatsource_general", type: "bigint", kind: "scalar", source: "trips[].seatSource.general" },
      { name: "subtotal", type: "bigint", kind: "scalar", source: "trips[].subtotal" },
      { name: "pax_foc", type: "bigint", kind: "scalar", source: "trips[].pax.foc" },
      { name: "nat_ad", type: "bigint", kind: "scalar", source: "trips[].nat.ad" },
      { name: "nat_chd", type: "bigint", kind: "scalar", source: "trips[].nat.chd" },
      { name: "nat_inf", type: "bigint", kind: "scalar", source: "trips[].nat.inf" },
      { name: "nat_foc", type: "bigint", kind: "scalar", source: "trips[].nat.foc" },
      { name: "lockdrawsel", type: "text", kind: "json_text", source: "trips[].lockDrawSel" },
      { name: "lockdraws", type: "text", kind: "json_text", source: "trips[].lockDraws" },
      { name: "ops_boatid", type: "text", kind: "scalar", source: "trips[].ops.boatId" },
      { name: "ops_vanid", type: "text", kind: "scalar", source: "trips[].ops.vanId" },
      { name: "ops_vanreturnid", type: "text", kind: "scalar", source: "trips[].ops.vanReturnId" },
      { name: "ops_returnsamevan", type: "boolean", kind: "scalar", source: "trips[].ops.returnSameVan" },
      { name: "ops_vangroup", type: "bigint", kind: "scalar", source: "trips[].ops.vanGroup" },
      { name: "ops_vanseq", type: "bigint", kind: "scalar", source: "trips[].ops.vanSeq" },
      { name: "ops_pickuptimefinal", type: "text", kind: "scalar", source: "trips[].ops.pickupTimeFinal" },
      { name: "ops_vansplits", type: "text", kind: "json_text", source: "trips[].ops.vanSplits" },
      { name: "ops_boatsplits", type: "text", kind: "json_text", source: "trips[].ops.boatSplits" },
      { name: "ops_reconfirm", type: "text", kind: "json_text", source: "trips[].ops.reconfirm" },
      { name: "ops_vancheckin", type: "text", kind: "json_text", source: "trips[].ops.vanCheckin" },
      { name: "ops_piercheckin", type: "text", kind: "json_text", source: "trips[].ops.pierCheckin" },
      { name: "ops_piernote", type: "text", kind: "json_text", source: "trips[].ops.pierNote" },
      { name: "promoid", type: "text", kind: "scalar", source: "trips[].promoId", note: "the promotion that priced this trip when it was sold · NULL = none, or sold before 029" },
    ],
  },
  {
    table: "sb_bookings__addons",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_bookings_id", references: "sb_bookings.id" }],
    columns: [
      { name: "sb_bookings_id", type: "text", kind: "fk", source: "(link) sb_bookings.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in addOns[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "type", type: "text", kind: "scalar", source: "addOns[].type" },
      { name: "label", type: "text", kind: "scalar", source: "addOns[].label" },
      { name: "amount", type: "bigint", kind: "scalar", source: "addOns[].amount" },
      { name: "qty", type: "bigint", kind: "scalar", source: "addOns[].qty" },
      { name: "note", type: "text", kind: "scalar", source: "addOns[].note" },
      { name: "jad", type: "bigint", kind: "scalar", source: "addOns[].jAd", note: "longtail-join · ผู้ใหญ่ที่ลงหางยาวจริง · ว่าง = ไม่ได้ระบุ ตัวอ่านคิดทุกหัวเหมือนเดิม" },
      { name: "jchd", type: "bigint", kind: "scalar", source: "addOns[].jChd", note: "longtail-join · เด็กที่ลงหางยาวจริง · ว่าง = ไม่ได้ระบุ" },
    ],
  },
  {
    table: "sb_bookings__history",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_bookings_id", references: "sb_bookings.id" }],
    columns: [
      { name: "sb_bookings_id", type: "text", kind: "fk", source: "(link) sb_bookings.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in history[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "at", type: "text", kind: "scalar", source: "history[].at" },
      { name: "kind", type: "text", kind: "scalar", source: "history[].kind" },
      { name: "text", type: "text", kind: "scalar", source: "history[].text" },
      { name: "tag", type: "text", kind: "scalar", source: "history[].tag" },
      { name: "by", type: "text", kind: "scalar", source: "history[].by" },
    ],
  },
  {
    table: "sb_bookings__upgrades",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_bookings_id", references: "sb_bookings.id" }],
    columns: [
      { name: "sb_bookings_id", type: "text", kind: "fk", source: "(link) sb_bookings.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in upgrades[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "id", type: "text", kind: "scalar", source: "upgrades[].id" },
      { name: "label", type: "text", kind: "scalar", source: "upgrades[].label" },
      { name: "sellprice", type: "bigint", kind: "scalar", source: "upgrades[].sellPrice" },
      { name: "tocompany", type: "bigint", kind: "scalar", source: "upgrades[].toCompany" },
      { name: "commission", type: "bigint", kind: "scalar", source: "upgrades[].commission" },
      { name: "collected", type: "boolean", kind: "scalar", source: "upgrades[].collected" },
      { name: "note", type: "text", kind: "scalar", source: "upgrades[].note" },
      { name: "seller", type: "text", kind: "scalar", source: "upgrades[].seller" },
      { name: "settle", type: "text", kind: "scalar", source: "upgrades[].settle" },
      { name: "at", type: "text", kind: "scalar", source: "upgrades[].at" },
      { name: "method", type: "text", kind: "scalar", source: "upgrades[].method" },
      { name: "feepct", type: "double precision", kind: "scalar", source: "upgrades[].feePct" },
      { name: "fee", type: "bigint", kind: "scalar", source: "upgrades[].fee" },
      { name: "customerpaid", type: "bigint", kind: "scalar", source: "upgrades[].customerPaid" },
      { name: "slips", type: "text", kind: "json_text", source: "upgrades[].slips" },
    ],
  },
  {
    table: "sb_bookings__feeitems",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_bookings_id", references: "sb_bookings.id" }],
    columns: [
      { name: "sb_bookings_id", type: "text", kind: "fk", source: "(link) sb_bookings.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in feeItems[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "type", type: "text", kind: "scalar", source: "feeItems[].type" },
      { name: "label", type: "text", kind: "scalar", source: "feeItems[].label" },
      { name: "amount", type: "bigint", kind: "scalar", source: "feeItems[].amount" },
      { name: "at", type: "text", kind: "scalar", source: "feeItems[].at" },
    ],
  },
  {
    table: "sb_bookings__partialcancels",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_bookings_id", references: "sb_bookings.id" }],
    columns: [
      { name: "sb_bookings_id", type: "text", kind: "fk", source: "(link) sb_bookings.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in partialCancels[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "date", type: "text", kind: "scalar", source: "partialCancels[].date" },
      { name: "tripidx", type: "bigint", kind: "scalar", source: "partialCancels[].tripIdx" },
      { name: "paxremoved_foc_th", type: "bigint", kind: "scalar", source: "partialCancels[].paxRemoved.foc_th" },
      { name: "count", type: "bigint", kind: "scalar", source: "partialCancels[].count" },
      { name: "category", type: "text", kind: "scalar", source: "partialCancels[].category" },
      { name: "categorylabel", type: "text", kind: "scalar", source: "partialCancels[].categoryLabel" },
      { name: "group", type: "text", kind: "scalar", source: "partialCancels[].group" },
      { name: "note", type: "text", kind: "scalar", source: "partialCancels[].note" },
      { name: "refundmode", type: "text", kind: "scalar", source: "partialCancels[].refundMode" },
      { name: "refund", type: "bigint", kind: "scalar", source: "partialCancels[].refund" },
      { name: "charged_count", type: "bigint", kind: "scalar", source: "partialCancels[].charged.count" },
      { name: "charged_amount", type: "bigint", kind: "scalar", source: "partialCancels[].charged.amount" },
      { name: "waived_count", type: "bigint", kind: "scalar", source: "partialCancels[].waived.count" },
      { name: "waived_amount", type: "bigint", kind: "scalar", source: "partialCancels[].waived.amount" },
      { name: "at", type: "text", kind: "scalar", source: "partialCancels[].at" },
      { name: "by", type: "text", kind: "scalar", source: "partialCancels[].by" },
      { name: "paxremoved_ad_fr", type: "bigint", kind: "scalar", source: "partialCancels[].paxRemoved.ad_fr" },
    ],
  },
  {
    table: "sb_bookings__adjustments",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_bookings_id", references: "sb_bookings.id" }],
    columns: [
      { name: "sb_bookings_id", type: "text", kind: "fk", source: "(link) sb_bookings.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in adjustments[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "kind", type: "text", kind: "scalar", source: "adjustments[].kind" },
      { name: "mode", type: "text", kind: "scalar", source: "adjustments[].mode" },
      { name: "value", type: "bigint", kind: "scalar", source: "adjustments[].value" },
      { name: "label", type: "text", kind: "scalar", source: "adjustments[].label" },
      { name: "note", type: "text", kind: "scalar", source: "adjustments[].note" },
    ],
  },
  {
    table: "sb_bookings__over",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_bookings_id", references: "sb_bookings.id" }],
    columns: [
      { name: "sb_bookings_id", type: "text", kind: "fk", source: "(link) sb_bookings.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in approval.over[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "routeid", type: "text", kind: "scalar", source: "approval.over[].routeId" },
      { name: "date", type: "text", kind: "scalar", source: "approval.over[].date" },
      { name: "name", type: "text", kind: "scalar", source: "approval.over[].name" },
      { name: "need", type: "bigint", kind: "scalar", source: "approval.over[].need" },
      { name: "capfree", type: "bigint", kind: "scalar", source: "approval.over[].capFree" },
      { name: "overby", type: "bigint", kind: "scalar", source: "approval.over[].overBy" },
      { name: "licfree", type: "bigint", kind: "scalar", source: "approval.over[].licFree" },
    ],
  },
];
