'use strict';

// sb_pickup_time_profiles and its child tables. Column format: data-model/README.md
module.exports = [
  {
    table: "sb_pickup_time_profiles",
    primaryKey: "id",
    foreignKeys: [],
    columns: [
      { name: "id", type: "text", kind: "pk", source: "sb_pickup_time_profiles[].id (record id; generated if absent)" },
      { name: "name", type: "text", kind: "scalar", source: "name" },
      { name: "from", type: "text", kind: "scalar", source: "from" },
      { name: "to", type: "text", kind: "scalar", source: "to" },
      { name: "notes", type: "text", kind: "scalar", source: "notes" },
      { name: "clonedfrom", type: "text", kind: "scalar", source: "clonedFrom" },
      { name: "createdat", type: "text", kind: "scalar", source: "createdAt" },
    ],
  },
  {
    table: "sb_pickup_time_profiles__times",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_pickup_time_profiles_id", references: "sb_pickup_time_profiles.id" }],
    columns: [
      { name: "sb_pickup_time_profiles_id", type: "text", kind: "fk", source: "(link) sb_pickup_time_profiles.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of times)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "pk_maikhao", type: "text", kind: "scalar", source: "times[key].pk-maikhao" },
      { name: "pk_naithon", type: "text", kind: "scalar", source: "times[key].pk-naithon" },
      { name: "pk_naiyang", type: "text", kind: "scalar", source: "times[key].pk-naiyang" },
      { name: "pk_airport", type: "text", kind: "scalar", source: "times[key].pk-airport" },
      { name: "pk_talang", type: "text", kind: "scalar", source: "times[key].pk-talang" },
      { name: "pk_aopor", type: "text", kind: "scalar", source: "times[key].pk-aopor" },
      { name: "pk_pakhlok", type: "text", kind: "scalar", source: "times[key].pk-pakhlok" },
      { name: "pk_yamu", type: "text", kind: "scalar", source: "times[key].pk-yamu" },
      { name: "pk_monument", type: "text", kind: "scalar", source: "times[key].pk-monument" },
      { name: "pk_kokaeo", type: "text", kind: "scalar", source: "times[key].pk-kokaeo" },
      { name: "pk_sapam", type: "text", kind: "scalar", source: "times[key].pk-sapam" },
      { name: "pk_layan", type: "text", kind: "scalar", source: "times[key].pk-layan" },
      { name: "pk_laguna", type: "text", kind: "scalar", source: "times[key].pk-laguna" },
      { name: "pk_bangtao", type: "text", kind: "scalar", source: "times[key].pk-bangtao" },
      { name: "pk_cherngtalay", type: "text", kind: "scalar", source: "times[key].pk-cherngtalay" },
      { name: "pk_surin", type: "text", kind: "scalar", source: "times[key].pk-surin" },
      { name: "pk_kamala", type: "text", kind: "scalar", source: "times[key].pk-kamala" },
      { name: "pk_kalim", type: "text", kind: "scalar", source: "times[key].pk-kalim" },
      { name: "pk_tritrang", type: "text", kind: "scalar", source: "times[key].pk-tritrang" },
      { name: "pk_patong", type: "text", kind: "scalar", source: "times[key].pk-patong" },
      { name: "pk_karon", type: "text", kind: "scalar", source: "times[key].pk-karon" },
      { name: "pk_kata", type: "text", kind: "scalar", source: "times[key].pk-kata" },
      { name: "pk_rawai", type: "text", kind: "scalar", source: "times[key].pk-rawai" },
      { name: "pk_naiharn", type: "text", kind: "scalar", source: "times[key].pk-naiharn" },
      { name: "pk_saiyuan", type: "text", kind: "scalar", source: "times[key].pk-saiyuan" },
      { name: "pk_chalong", type: "text", kind: "scalar", source: "times[key].pk-chalong" },
      { name: "pk_chaofa", type: "text", kind: "scalar", source: "times[key].pk-chaofa" },
      { name: "pk_siray", type: "text", kind: "scalar", source: "times[key].pk-siray" },
      { name: "pk_town", type: "text", kind: "scalar", source: "times[key].pk-town" },
      { name: "pk_aoyon", type: "text", kind: "scalar", source: "times[key].pk-aoyon" },
      { name: "pk_panwa", type: "text", kind: "scalar", source: "times[key].pk-panwa" },
      { name: "nt_panwa_pier", type: "text", kind: "scalar", source: "times[key].nt-panwa-pier" },
      { name: "pk_kathu", type: "text", kind: "scalar", source: "times[key].pk-kathu" },
      { name: "pk_khokkloi", type: "text", kind: "scalar", source: "times[key].pk-khokkloi" },
      { name: "pk_natai", type: "text", kind: "scalar", source: "times[key].pk-natai" },
      { name: "nt_tublamu_pier", type: "text", kind: "scalar", source: "times[key].nt-tublamu-pier" },
      { name: "kl_numkhem", type: "text", kind: "scalar", source: "times[key].kl-numkhem" },
      { name: "kl_bangsak", type: "text", kind: "scalar", source: "times[key].kl-bangsak" },
      { name: "kl_pakwip", type: "text", kind: "scalar", source: "times[key].kl-pakwip" },
      { name: "kl_pakarang", type: "text", kind: "scalar", source: "times[key].kl-pakarang" },
      { name: "kl_khukkhak", type: "text", kind: "scalar", source: "times[key].kl-khukkhak" },
      { name: "kl_bangniang", type: "text", kind: "scalar", source: "times[key].kl-bangniang" },
      { name: "kl_nanglao", type: "text", kind: "scalar", source: "times[key].kl-nanglao" },
      { name: "kl_center", type: "text", kind: "scalar", source: "times[key].kl-center" },
      { name: "kl_khaolak", type: "text", kind: "scalar", source: "times[key].kl-khaolak" },
      { name: "kl_merlin", type: "text", kind: "scalar", source: "times[key].kl-merlin" },
      { name: "kl_poseidon", type: "text", kind: "scalar", source: "times[key].kl-poseidon" },
      { name: "kl_tublamuhotel", type: "text", kind: "scalar", source: "times[key].kl-tublamuhotel" },
    ],
  },
];
