'use strict';

// sb_rate_types and its child tables. Column format: data-model/README.md
module.exports = [
  {
    table: "sb_rate_types",
    primaryKey: "id",
    foreignKeys: [],
    columns: [
      { name: "id", type: "text", kind: "pk", source: "sb_rate_types[].id (record id; generated if absent)" },
      { name: "code", type: "text", kind: "scalar", source: "code" },
      { name: "name", type: "text", kind: "scalar", source: "name" },
      { name: "note", type: "text", kind: "scalar", source: "note" },
      { name: "color", type: "text", kind: "scalar", source: "color" },
      { name: "createddate", type: "text", kind: "scalar", source: "createdDate" },
      { name: "validfrom", type: "text", kind: "scalar", source: "validFrom" },
      { name: "validto", type: "text", kind: "scalar", source: "validTo" },
      { name: "active", type: "boolean", kind: "scalar", source: "active" },
      { name: "pricetiers", type: "text", kind: "json_text", source: "priceTiers", note: "3-tier contract pricing · {route:{zone:{paxType:{sell,minSell}}}} · seatRates stays the NET tier that booking bills from" },
      { name: "nationalityscope", type: "text", kind: "scalar", source: "nationalityScope" },
      { name: "owner", type: "text", kind: "scalar", source: "owner", note: "rate-type owner = sales id · '' = Shared/central (visible to all)" },
    ],
  },
  {
    table: "sb_rate_types__routes",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_rate_types_id", references: "sb_rate_types.id" }],
    columns: [
      { name: "sb_rate_types_id", type: "text", kind: "fk", source: "(link) sb_rate_types.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in routes[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "value", type: "text", kind: "array_scalar", source: "routes[] (element)" },
    ],
  },
  {
    table: "sb_rate_types__seatrates",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_rate_types_id", references: "sb_rate_types.id" }],
    columns: [
      { name: "sb_rate_types_id", type: "text", kind: "fk", source: "(link) sb_rate_types.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of seatRates)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "pk_adult_thai", type: "bigint", kind: "scalar", source: "seatRates[key].PK.adult-thai" },
      { name: "pk_adult_fr", type: "bigint", kind: "scalar", source: "seatRates[key].PK.adult-fr" },
      { name: "pk_child_thai", type: "bigint", kind: "scalar", source: "seatRates[key].PK.child-thai" },
      { name: "pk_child_fr", type: "bigint", kind: "scalar", source: "seatRates[key].PK.child-fr" },
      { name: "pk_infant_thai", type: "bigint", kind: "scalar", source: "seatRates[key].PK.infant-thai" },
      { name: "pk_infant_fr", type: "bigint", kind: "scalar", source: "seatRates[key].PK.infant-fr" },
      { name: "kl_adult_thai", type: "bigint", kind: "scalar", source: "seatRates[key].KL.adult-thai" },
      { name: "kl_adult_fr", type: "bigint", kind: "scalar", source: "seatRates[key].KL.adult-fr" },
      { name: "kl_child_thai", type: "bigint", kind: "scalar", source: "seatRates[key].KL.child-thai" },
      { name: "kl_child_fr", type: "bigint", kind: "scalar", source: "seatRates[key].KL.child-fr" },
      { name: "kl_infant_thai", type: "bigint", kind: "scalar", source: "seatRates[key].KL.infant-thai" },
      { name: "kl_infant_fr", type: "bigint", kind: "scalar", source: "seatRates[key].KL.infant-fr" },
      { name: "notransfer_adult_thai", type: "bigint", kind: "scalar", source: "seatRates[key].NoTransfer.adult-thai" },
      { name: "notransfer_adult_fr", type: "bigint", kind: "scalar", source: "seatRates[key].NoTransfer.adult-fr" },
      { name: "notransfer_child_thai", type: "bigint", kind: "scalar", source: "seatRates[key].NoTransfer.child-thai" },
      { name: "notransfer_child_fr", type: "bigint", kind: "scalar", source: "seatRates[key].NoTransfer.child-fr" },
      { name: "notransfer_infant_thai", type: "bigint", kind: "scalar", source: "seatRates[key].NoTransfer.infant-thai" },
      { name: "notransfer_infant_fr", type: "bigint", kind: "scalar", source: "seatRates[key].NoTransfer.infant-fr" },
      { name: "kl", type: "text", kind: "json_text", source: "seatRates[key].KL" },
    ],
  },
  {
    table: "sb_rate_types__charterrates",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_rate_types_id", references: "sb_rate_types.id" }],
    columns: [
      { name: "sb_rate_types_id", type: "text", kind: "fk", source: "(link) sb_rate_types.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of charterRates)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "speedboat_starterprice", type: "bigint", kind: "scalar", source: "charterRates[key].speedboat.starterPrice" },
      { name: "speedboat_starterincludes", type: "bigint", kind: "scalar", source: "charterRates[key].speedboat.starterIncludes" },
      { name: "speedboat_extraperpax", type: "bigint", kind: "scalar", source: "charterRates[key].speedboat.extraPerPax" },
      { name: "catamaran_starterprice", type: "bigint", kind: "scalar", source: "charterRates[key].catamaran.starterPrice" },
      { name: "catamaran_starterincludes", type: "bigint", kind: "scalar", source: "charterRates[key].catamaran.starterIncludes" },
      { name: "catamaran_extraperpax", type: "bigint", kind: "scalar", source: "charterRates[key].catamaran.extraPerPax" },
    ],
  },
  {
    table: "sb_rate_types__addons",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_rate_types_id", references: "sb_rate_types.id" }],
    columns: [
      { name: "sb_rate_types_id", type: "text", kind: "fk", source: "(link) sb_rate_types.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of addOns)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "adult", type: "bigint", kind: "scalar", source: "addOns[key].adult" },
      { name: "child", type: "bigint", kind: "scalar", source: "addOns[key].child" },
      { name: "unit", type: "text", kind: "scalar", source: "addOns[key].unit" },
      { name: "join_adult", type: "bigint", kind: "scalar", source: "addOns[key].join.adult" },
      { name: "join_child", type: "bigint", kind: "scalar", source: "addOns[key].join.child" },
      { name: "charter_price", type: "bigint", kind: "scalar", source: "addOns[key].charter.price" },
      { name: "charter_capacity", type: "bigint", kind: "scalar", source: "addOns[key].charter.capacity" },
    ],
  },
  {
    table: "sb_rate_types__addons__applies",
    primaryKey: "row_pk",
    foreignKeys: [],
    columns: [
      { name: "sb_rate_types_addons_id", type: "text", kind: "fk", source: "(link) sb_rate_types__addons.id" },
      { name: "idx", type: "bigint", kind: "synthetic", source: "(order) position in addOns[key].applies[]" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "value", type: "text", kind: "array_scalar", source: "addOns[key].applies[] (element)" },
    ],
  },
  {
    table: "sb_rate_types__addons__r5",
    primaryKey: "row_pk",
    foreignKeys: [],
    columns: [
      { name: "sb_rate_types_addons_id", type: "text", kind: "fk", source: "(link) sb_rate_types__addons.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of addOns[key].r5)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "sedan", type: "bigint", kind: "scalar", source: "addOns[key].r5[key].sedan" },
      { name: "van", type: "bigint", kind: "scalar", source: "addOns[key].r5[key].van" },
    ],
  },
  {
    table: "sb_rate_types__addons__r6",
    primaryKey: "row_pk",
    foreignKeys: [],
    columns: [
      { name: "sb_rate_types_addons_id", type: "text", kind: "fk", source: "(link) sb_rate_types__addons.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of addOns[key].r6)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "sedan", type: "bigint", kind: "scalar", source: "addOns[key].r6[key].sedan" },
      { name: "van", type: "bigint", kind: "scalar", source: "addOns[key].r6[key].van" },
    ],
  },
  {
    table: "sb_rate_types__addons__r10",
    primaryKey: "row_pk",
    foreignKeys: [],
    columns: [
      { name: "sb_rate_types_addons_id", type: "text", kind: "fk", source: "(link) sb_rate_types__addons.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of addOns[key].r10)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "sedan", type: "bigint", kind: "scalar", source: "addOns[key].r10[key].sedan" },
      { name: "van", type: "bigint", kind: "scalar", source: "addOns[key].r10[key].van" },
    ],
  },
  {
    table: "sb_rate_types__addons__r11",
    primaryKey: "row_pk",
    foreignKeys: [],
    columns: [
      { name: "sb_rate_types_addons_id", type: "text", kind: "fk", source: "(link) sb_rate_types__addons.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of addOns[key].r11)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "sedan", type: "bigint", kind: "scalar", source: "addOns[key].r11[key].sedan" },
      { name: "van", type: "bigint", kind: "scalar", source: "addOns[key].r11[key].van" },
    ],
  },
  {
    table: "sb_rate_types__addons__r12",
    primaryKey: "row_pk",
    foreignKeys: [],
    columns: [
      { name: "sb_rate_types_addons_id", type: "text", kind: "fk", source: "(link) sb_rate_types__addons.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of addOns[key].r12)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "sedan", type: "bigint", kind: "scalar", source: "addOns[key].r12[key].sedan" },
      { name: "van", type: "bigint", kind: "scalar", source: "addOns[key].r12[key].van" },
    ],
  },
  {
    table: "sb_rate_types__routevalidity",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_rate_types_id", references: "sb_rate_types.id" }],
    columns: [
      { name: "sb_rate_types_id", type: "text", kind: "fk", source: "(link) sb_rate_types.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of routeValidity)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "from", type: "text", kind: "scalar", source: "routeValidity[key].from" },
      { name: "to", type: "text", kind: "scalar", source: "routeValidity[key].to" },
    ],
  },
  {
    table: "sb_rate_types__addons__byroute",
    primaryKey: "row_pk",
    foreignKeys: [],
    columns: [
      { name: "sb_rate_types_addons_id", type: "text", kind: "fk", source: "(link) sb_rate_types__addons.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of addOns[key].byRoute)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "join_adult", type: "bigint", kind: "scalar", source: "addOns[key].byRoute[key].join.adult" },
      { name: "join_child", type: "bigint", kind: "scalar", source: "addOns[key].byRoute[key].join.child" },
      { name: "charter_price", type: "bigint", kind: "scalar", source: "addOns[key].byRoute[key].charter.price" },
      { name: "charter_capacity", type: "bigint", kind: "scalar", source: "addOns[key].byRoute[key].charter.capacity" },
    ],
  },
  {
    table: "sb_rate_types__addons__r4",
    primaryKey: "row_pk",
    foreignKeys: [],
    columns: [
      { name: "sb_rate_types_addons_id", type: "text", kind: "fk", source: "(link) sb_rate_types__addons.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of addOns[key].r4)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "sedan", type: "bigint", kind: "scalar", source: "addOns[key].r4[key].sedan" },
      { name: "van", type: "bigint", kind: "scalar", source: "addOns[key].r4[key].van" },
    ],
  },
  {
    table: "sb_rate_types__routebundles",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "sb_rate_types_id", references: "sb_rate_types.id" }],
    columns: [
      { name: "sb_rate_types_id", type: "text", kind: "fk", source: "(link) sb_rate_types.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of routeBundles)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "longtail_mode", type: "text", kind: "scalar", source: "routeBundles[key].longtail.mode" },
      { name: "longtail_adult", type: "bigint", kind: "scalar", source: "routeBundles[key].longtail.adult" },
      { name: "longtail_child", type: "bigint", kind: "scalar", source: "routeBundles[key].longtail.child" },
    ],
  },
];
