'use strict';

// trips and its child tables. Column format: data-model/README.md
module.exports = [
  {
    table: "trips",
    primaryKey: "id",
    foreignKeys: [],
    columns: [
      { name: "id", type: "text", kind: "pk", source: "trips map key (generated id)" },
      { name: "key", type: "text", kind: "map_key", source: "trips map key (original)" },
      { name: "b1_route", type: "text", kind: "scalar", source: "trips[key].b1.route" },
      { name: "b1_type", type: "text", kind: "scalar", source: "trips[key].b1.type" },
      { name: "b1_booked", type: "bigint", kind: "scalar", source: "trips[key].b1.booked" },
      { name: "b3_route", type: "text", kind: "scalar", source: "trips[key].b3.route" },
      { name: "b3_type", type: "text", kind: "scalar", source: "trips[key].b3.type" },
      { name: "b3_booked", type: "bigint", kind: "scalar", source: "trips[key].b3.booked" },
      { name: "b4_route", type: "text", kind: "scalar", source: "trips[key].b4.route" },
      { name: "b4_type", type: "text", kind: "scalar", source: "trips[key].b4.type" },
      { name: "b4_booked", type: "bigint", kind: "scalar", source: "trips[key].b4.booked" },
      { name: "b5_route", type: "text", kind: "scalar", source: "trips[key].b5.route" },
      { name: "b5_type", type: "text", kind: "scalar", source: "trips[key].b5.type" },
      { name: "b5_booked", type: "bigint", kind: "scalar", source: "trips[key].b5.booked" },
      { name: "b6_route", type: "text", kind: "scalar", source: "trips[key].b6.route" },
      { name: "b6_type", type: "text", kind: "scalar", source: "trips[key].b6.type" },
      { name: "b6_booked", type: "bigint", kind: "scalar", source: "trips[key].b6.booked" },
      { name: "b7_route", type: "text", kind: "scalar", source: "trips[key].b7.route" },
      { name: "b7_type", type: "text", kind: "scalar", source: "trips[key].b7.type" },
      { name: "b7_booked", type: "bigint", kind: "scalar", source: "trips[key].b7.booked" },
      { name: "b9_route", type: "text", kind: "scalar", source: "trips[key].b9.route" },
      { name: "b9_type", type: "text", kind: "scalar", source: "trips[key].b9.type" },
      { name: "b9_booked", type: "bigint", kind: "scalar", source: "trips[key].b9.booked" },
      { name: "b10_route", type: "text", kind: "scalar", source: "trips[key].b10.route" },
      { name: "b10_type", type: "text", kind: "scalar", source: "trips[key].b10.type" },
      { name: "b10_booked", type: "bigint", kind: "scalar", source: "trips[key].b10.booked" },
      { name: "b12_route", type: "text", kind: "scalar", source: "trips[key].b12.route" },
      { name: "b12_type", type: "text", kind: "scalar", source: "trips[key].b12.type" },
      { name: "b12_booked", type: "bigint", kind: "scalar", source: "trips[key].b12.booked" },
      { name: "b11_route", type: "text", kind: "scalar", source: "trips[key].b11.route" },
      { name: "b11_type", type: "text", kind: "scalar", source: "trips[key].b11.type" },
      { name: "b11_booked", type: "bigint", kind: "scalar", source: "trips[key].b11.booked" },
      { name: "b13_route", type: "text", kind: "scalar", source: "trips[key].b13.route" },
      { name: "b13_type", type: "text", kind: "scalar", source: "trips[key].b13.type" },
      { name: "b13_booked", type: "bigint", kind: "scalar", source: "trips[key].b13.booked" },
      { name: "b2_route", type: "text", kind: "scalar", source: "trips[key].b2.route" },
      { name: "b2_type", type: "text", kind: "scalar", source: "trips[key].b2.type" },
      { name: "b2_booked", type: "bigint", kind: "scalar", source: "trips[key].b2.booked" },
      { name: "b13_charterbookingid", type: "text", kind: "scalar", source: "trips[key].b13.charterBookingId" },
      { name: "b6_charterbookingid", type: "text", kind: "scalar", source: "trips[key].b6.charterBookingId" },
      { name: "b8_route", type: "text", kind: "scalar", source: "trips[key].b8.route" },
      { name: "b8_type", type: "text", kind: "scalar", source: "trips[key].b8.type" },
      { name: "b8_booked", type: "bigint", kind: "scalar", source: "trips[key].b8.booked" },
      { name: "b8_charterbookingid", type: "text", kind: "scalar", source: "trips[key].b8.charterBookingId" },
      { name: "b14_route", type: "text", kind: "scalar", source: "trips[key].b14.route" },
      { name: "b14_type", type: "text", kind: "scalar", source: "trips[key].b14.type" },
      { name: "b14_booked", type: "bigint", kind: "scalar", source: "trips[key].b14.booked" },
      { name: "b14_charterbookingid", type: "text", kind: "scalar", source: "trips[key].b14.charterBookingId" },
      { name: "b15_route", type: "text", kind: "scalar", source: "trips[key].b15.route" },
      { name: "b15_type", type: "text", kind: "scalar", source: "trips[key].b15.type" },
      { name: "b15_booked", type: "bigint", kind: "scalar", source: "trips[key].b15.booked" },
      { name: "b15_charterbookingid", type: "text", kind: "scalar", source: "trips[key].b15.charterBookingId" },
    ],
  },
  {
    table: "trips__boat",
    primaryKey: "row_pk",
    foreignKeys: [{ column: "trips_id", references: "trips.id" }],
    columns: [
      { name: "trips_id", type: "text", kind: "fk", source: "(link) trips.id" },
      { name: "key", type: "text", kind: "map_key", source: "(map key of trips[key].boats)" },
      { name: "row_pk", type: "text", kind: "synthetic-pk", source: "(generated child key)" },
      { name: "value", type: "text", kind: "map_value_json", source: "trips[key][boat] whole op object" },
    ],
  },
];
