// GENERATED by tools/gen-model-types.mjs from data-model/tables. Do not edit by hand:
// change the model, then run `npm run gen:models` in the repo root.

/** trips[date][boatId]: one boat's deployment on one day (Boat Operation). Open-ended, stored as JSON. */
export type TripDeployments = Record<string, Record<string, TripDeployment>>;
export interface TripDeployment {
  route?: string;
  type?: string;
  booked?: number;
  charterBookingId?: string;
  [field: string]: unknown;
}

/** fleet_daily[date][boatId]: Daily Fleet Log for one boat on one day. Open-ended, stored as JSON. */
export type FleetDailyLog = Record<string, Record<string, FleetDailyBoat>>;
export interface FleetDailyBoat {
  fuel?: number;
  paxActual?: number;
  /** tripKey -> that trip's engine readings etc. */
  trips?: Record<string, unknown>;
  [field: string]: unknown;
}

/** Table `routes`. */
export interface Route {
  id: string;
  name?: string;
  islands?: string;
  mealVenueId?: string;
  color?: string;
  pier?: string;
  kind?: string;
  dailyCap?: number;
  familyId?: string;
  sort?: number;
  code?: string;
  extId?: string;
  times?: string[];
  seasons?: RouteSeason[];
  overrides?: Record<string, unknown>;
}

/** Table `routes__seasons`. */
export interface RouteSeason {
  id?: string;
  type?: string;
  from?: string;
  to?: string;
}

/** Table `boats`. */
export interface Boat {
  id: string;
  name?: string;
  nameTh?: string;
  type?: string;
  pier?: string;
  cap?: number;
  engineCount?: number;
  use?: string;
  material?: string;
  reg?: string;
  callsign?: string;
  imo?: string;
  year?: string;
  homeportCity?: string;
  gt?: number;
  nt?: number;
  dwt?: string;
  loa?: number;
  beam?: number;
  depth?: number;
  draft?: string;
  lbp?: number;
  bhp?: number;
  licensePax?: number;
  crew?: number;
  fishcrew?: string;
  totalcap?: number;
  owner?: string;
  homeport?: string;
  ownerAddr?: string;
  note?: string;
  color?: string;
  ownership?: string;
  retired?: boolean;
  docs?: BoatDoc[];
  log?: BoatLog[];
  repairHistory?: BoatRepairHistory[];
  assignments?: BoatAssignment[];
}

/** Table `boats__docs`. */
export interface BoatDoc {
  name?: string;
  exp?: string;
  renewStatus?: string;
}

/** Table `boats__log`. */
export interface BoatLog {
  id?: string;
  s?: string;
  from?: string;
  to?: string;
  loc?: string;
  note?: string;
  province?: string;
  locType?: string;
  detail?: string;
  reason?: string;
  projectId?: string;
}

/** Table `boats__repairhistory`. */
export interface BoatRepairHistory {
  date?: string;
  jobNo?: string;
  title?: string;
  detail?: string;
  type?: string;
  location?: string;
  cost?: number;
  startDate?: string;
  endDate?: string;
  outcome?: string;
  closeNote?: string;
  assets?: string[];
}

/** Table `boats__assignments`. */
export interface BoatAssignment {
  id?: string;
  type?: string;
  fromPier?: string;
  toPier?: string;
  startDate?: string;
  endDate?: string;
  reason?: string;
  cost?: number;
  status?: string;
  createdDate?: string;
}

/** Table `fleet_engines`. */
export interface FleetEngine {
  id: string;
  brand?: string;
  model?: string;
  serial?: string;
  hp?: number;
  boatId?: string;
  pos?: string;
  status?: string;
  baseHours?: number;
  serviceInterval?: number;
  buyDate?: string;
  note?: string;
  spareLocation?: string;
  price?: string;
  lastServiceHours?: number;
  lastServiceDate?: string;
  log?: FleetEngineLog[];
}

/** Table `fleet_engines__log`. */
export interface FleetEngineLog {
  date?: string;
  type?: string;
  desc?: string;
  detail?: string;
  hours?: number;
  by?: string;
  cost?: number;
  outcome?: string;
  engineHours?: number;
  text?: string;
}

/** Table `fleet_gearboxes`. */
export interface FleetGearbox {
  id: string;
  boatId?: string;
  engineId?: string;
  brand?: string;
  model?: string;
  serial?: string;
  status?: string;
  baseHours?: number;
  buyDate?: string;
  note?: string;
  spareLocation?: string;
  shaftLength?: string;
  modelSuffix?: string;
  installHours?: number;
  rotation?: string;
  gearRatio?: string;
  oilCapacity?: string;
  serviceInterval?: number;
  lastServiceDate?: string;
  onBoatId?: string;
  onBoatPos?: string;
  log?: FleetGearboxLog[];
}

/** Table `fleet_gearboxes__log`. */
export interface FleetGearboxLog {
  date?: string;
  type?: string;
  desc?: string;
  engineHours?: number;
  fromLoc?: string;
  toLoc?: string;
  usedHours?: number;
  incidentId?: string;
  outcome?: string;
  detail?: string;
  text?: string;
}

/** Table `fleet_propellers`. */
export interface FleetPropeller {
  id: string;
  boatId?: string;
  gearboxId?: string;
  brand?: string;
  serial?: string;
  diameter?: number;
  pitch?: number;
  size?: string;
  blades?: string;
  material?: string;
  rotation?: string;
  hubSize?: string;
  cupping?: string;
  cost?: number;
  status?: string;
  buyDate?: string;
  note?: string;
  spareLocation?: string;
  oldSerial?: string;
  propPos?: string;
  engineId?: string;
  log?: FleetPropellerLog[];
}

/** Table `fleet_propellers__log`. */
export interface FleetPropellerLog {
  date?: string;
  type?: string;
  desc?: string;
  engineHours?: number;
  fromLoc?: string;
  toLoc?: string;
  incidentId?: string;
  detail?: string;
  outcome?: string;
}

/** Table `fleet_maintenance`. */
export interface FleetMaintenance {
  id: string;
  no?: string;
  boatId?: string;
  type?: string;
  title?: string;
  detail?: string;
  location?: string;
  status?: string;
  startDate?: string;
  endDate?: string;
  cost?: number;
  incidentId?: string;
  boatStatus?: string;
  boatStatusReason?: string;
  setFixing?: boolean;
  outcome?: string;
  parentProjectId?: string;
  awaitingInvoice?: boolean;
  closeNote?: string;
  assets?: FleetMaintenanceAsset[];
  progressLog?: FleetMaintenanceProgressLog[];
  parts?: FleetMaintenancePart[];
}

/** Table `fleet_maintenance__assets`. */
export interface FleetMaintenanceAsset {
  type?: string;
  engId?: string;
  label?: string;
  detail?: string;
  status?: string;
  gbId?: string;
  propId?: string;
  id?: string;
}

/** Table `fleet_maintenance__progresslog`. */
export interface FleetMaintenanceProgressLog {
  date?: string;
  text?: string;
  by?: string;
  createdAt?: string;
}

/** Table `fleet_maintenance__parts`. */
export interface FleetMaintenancePart {
  invId?: string;
  name?: string;
  qty?: number;
  unit?: string;
  cost?: number;
  location?: string;
  date?: string;
}

/** Table `fleet_incidents`. */
export interface FleetIncident {
  id: string;
  no?: string;
  boatId?: string;
  date?: string;
  time?: string;
  title?: string;
  detail?: string;
  remark?: string;
  priority?: number;
  severity?: string;
  type?: string;
  status?: string;
  maintId?: string;
  closedDate?: string;
  quickFix?: boolean;
  resolvedDate?: string;
  damagedAssets?: FleetIncidentDamagedAsset[];
  progressLog?: FleetIncidentProgressLog[];
  relatedMaintIds?: string[];
}

/** Table `fleet_incidents__damagedassets`. */
export interface FleetIncidentDamagedAsset {
  type?: string;
  id?: string;
  label?: string;
  swapped?: boolean;
  swappedTo?: string;
  swappedDate?: string;
  engId?: string;
  gbId?: string;
  propId?: string;
}

/** Table `fleet_incidents__progresslog`. */
export interface FleetIncidentProgressLog {
  date?: string;
  text?: string;
  by?: string;
  createdAt?: string;
}

/** Table `fleet_inventory`. */
export interface FleetInventory {
  id: string;
  name?: string;
  partNo?: string;
  category?: string;
  supplier?: string;
  location?: string;
  unit?: string;
  qty?: number;
  minQty?: number;
  cost?: number;
  note?: string;
  totalQty?: number;
  primaryLocation?: string;
  createdDate?: string;
  createdFrom?: string;
  history?: FleetInventoryHistory[];
  stocks?: FleetInventoryStock[];
}

/** Table `fleet_inventory__history`. */
export interface FleetInventoryHistory {
  date?: string;
  type?: string;
  qty?: number;
  note?: string;
  by?: string;
  location?: string;
  jobId?: string;
  consumeId?: string;
  desc?: string;
  changes?: FleetInventoryHistoryChange[];
}

/** Table `fleet_inventory__history__changes`. */
export interface FleetInventoryHistoryChange {
  field?: string;
  from?: string;
  to?: string;
}

/** Table `fleet_inventory__stocks`. */
export interface FleetInventoryStock {
  location?: string;
  qty?: number;
  minQty?: number;
}

/** Table `fleet_memos`. */
export interface FleetMemo {
  id: string;
  no?: string;
  title?: string;
  boatId?: string;
  memoType?: string;
  proposer?: string;
  from?: string;
  to?: string;
  cc?: string;
  createdDate?: string;
  status?: string;
  currentStep?: number;
  vatEnabled?: boolean;
  vatRate?: number;
  refNote?: string;
  subtotal?: number;
  discount?: number;
  vat?: number;
  amount?: number;
  approvedBy?: string;
  approvedDate?: string;
  approveNote?: string;
  orderedDate?: string;
  receivedDate?: string;
  supplier?: string;
  discountPct?: number;
  maintId?: string;
  scope?: string;
  generalCategory?: string;
  note?: string;
  orderedBy?: string;
  receivedBy?: string;
  paidDate?: string;
  paidBy?: string;
  paidVia?: string;
  discountAmt?: number;
  afterDiscount?: number;
  receivedLocation?: string;
  receivedSummary?: string;
  projectId?: string;
  items?: FleetMemoItem[];
}

/** Table `fleet_memos__items`. */
export interface FleetMemoItem {
  name?: string;
  qty?: number;
  price?: number;
  category?: string;
  partNo?: string;
  invId?: string;
  unit?: string;
  fromInventory?: boolean;
  discountPct?: number;
  autoRegister?: boolean;
  inventorySnapshot?: {
    cost?: number;
    primaryLocation?: string;
    qtyAtSelection?: number;
  };
}

/** Table `sb_rate_types`. */
export interface SbRateType {
  id: string;
  code?: string;
  name?: string;
  note?: string;
  color?: string;
  createdDate?: string;
  validFrom?: string;
  validTo?: string;
  active?: boolean;
  priceTiers?: unknown;
  nationalityScope?: string;
  owner?: string;
  routes?: string[];
  seatRates?: Record<string, SbRateTypeSeatRate>;
  charterRates?: Record<string, SbRateTypeCharterRate>;
  addOns?: Record<string, SbRateTypeAddOn>;
  routeValidity?: Record<string, SbRateTypeRouteValidity>;
  routeBundles?: Record<string, SbRateTypeRouteBundle>;
}

/** Table `sb_rate_types__seatrates`. */
export interface SbRateTypeSeatRate {
  PK?: {
    "adult-thai"?: number;
    "adult-fr"?: number;
    "child-thai"?: number;
    "child-fr"?: number;
    "infant-thai"?: number;
    "infant-fr"?: number;
  };
  KL?: {
    "adult-thai"?: number;
    "adult-fr"?: number;
    "child-thai"?: number;
    "child-fr"?: number;
    "infant-thai"?: number;
    "infant-fr"?: number;
  };
  NoTransfer?: {
    "adult-thai"?: number;
    "adult-fr"?: number;
    "child-thai"?: number;
    "child-fr"?: number;
    "infant-thai"?: number;
    "infant-fr"?: number;
  };
}

/** Table `sb_rate_types__charterrates`. */
export interface SbRateTypeCharterRate {
  speedboat?: {
    starterPrice?: number;
    starterIncludes?: number;
    extraPerPax?: number;
  };
  catamaran?: {
    starterPrice?: number;
    starterIncludes?: number;
    extraPerPax?: number;
  };
}

/** Table `sb_rate_types__addons`. */
export interface SbRateTypeAddOn {
  adult?: number;
  child?: number;
  unit?: string;
  join?: {
    adult?: number;
    child?: number;
  };
  charter?: {
    price?: number;
    capacity?: number;
  };
  applies?: string[];
  r5?: Record<string, SbRateTypeAddOnR5>;
  r6?: Record<string, SbRateTypeAddOnR6>;
  r10?: Record<string, SbRateTypeAddOnR10>;
  r11?: Record<string, SbRateTypeAddOnR11>;
  r12?: Record<string, SbRateTypeAddOnR12>;
  byRoute?: Record<string, SbRateTypeAddOnByRoute>;
  r4?: Record<string, SbRateTypeAddOnR4>;
}

/** Table `sb_rate_types__addons__r5`. */
export interface SbRateTypeAddOnR5 {
  sedan?: number;
  van?: number;
}

/** Table `sb_rate_types__addons__r6`. */
export interface SbRateTypeAddOnR6 {
  sedan?: number;
  van?: number;
}

/** Table `sb_rate_types__addons__r10`. */
export interface SbRateTypeAddOnR10 {
  sedan?: number;
  van?: number;
}

/** Table `sb_rate_types__addons__r11`. */
export interface SbRateTypeAddOnR11 {
  sedan?: number;
  van?: number;
}

/** Table `sb_rate_types__addons__r12`. */
export interface SbRateTypeAddOnR12 {
  sedan?: number;
  van?: number;
}

/** Table `sb_rate_types__addons__byroute`. */
export interface SbRateTypeAddOnByRoute {
  join?: {
    adult?: number;
    child?: number;
  };
  charter?: {
    price?: number;
    capacity?: number;
  };
}

/** Table `sb_rate_types__addons__r4`. */
export interface SbRateTypeAddOnR4 {
  sedan?: number;
  van?: number;
}

/** Table `sb_rate_types__routevalidity`. */
export interface SbRateTypeRouteValidity {
  from?: string;
  to?: string;
}

/** Table `sb_rate_types__routebundles`. */
export interface SbRateTypeRouteBundle {
  longtail?: {
    mode?: string;
    adult?: number;
    child?: number;
  };
}

/** Table `sb_agents_rate_bindings`. */
export interface SbAgentsRateBinding {
  id: string;
  rateTypeId?: string;
}

/** Table `fleet_safety`. */
export interface FleetSafety {
  id: string;
  boatId?: string;
  category?: string;
  name?: string;
  brand?: string;
  model?: string;
  serial?: string;
  qty?: number;
  installDate?: string;
  expiryDate?: string;
  nextPM?: string;
  lastInspect?: string;
  status?: string;
  location?: string;
  note?: string;
  log?: FleetSafetyLog[];
  inspections?: FleetSafetyInspection[];
}

/** Table `fleet_safety__log`. */
export interface FleetSafetyLog {
  date?: string;
  type?: string;
  desc?: string;
}

/** Table `fleet_safety__inspections`. */
export interface FleetSafetyInspection {
  id?: string;
  date?: string;
  result?: string;
  note?: string;
  by?: string;
}

/** Table `sb_pickup_areas`. */
export interface SbPickupArea {
  id: string;
  name?: string;
  zone?: string;
  region?: string;
  timeGroup?: string;
}

/** Table `sb_pickup_times`. */
export interface SbPickupTime {
  "pk-n1"?: string;
  "pk-n2"?: string;
  "pk-e1"?: string;
  "pk-e2"?: string;
  "pk-wn1"?: string;
  "pk-w1"?: string;
  "pk-w2"?: string;
  "pk-s1"?: string;
  "pk-s2"?: string;
  "pk-c1"?: string;
  "pk-c2"?: string;
  "pk-pa1"?: string;
  "nt-vp"?: string;
  "pk-pn1"?: string;
  "nt-tl"?: string;
}

/** Table `sb_pickup_time_profiles`. */
export interface SbPickupTimeProfile {
  id: string;
  name?: string;
  from?: string;
  to?: string;
  notes?: string;
  clonedFrom?: string;
  createdAt?: string;
  times?: Record<string, SbPickupTimeProfileTime>;
}

/** Table `sb_pickup_time_profiles__times`. */
export interface SbPickupTimeProfileTime {
  "pk-maikhao"?: string;
  "pk-naithon"?: string;
  "pk-naiyang"?: string;
  "pk-airport"?: string;
  "pk-talang"?: string;
  "pk-aopor"?: string;
  "pk-pakhlok"?: string;
  "pk-yamu"?: string;
  "pk-monument"?: string;
  "pk-kokaeo"?: string;
  "pk-sapam"?: string;
  "pk-layan"?: string;
  "pk-laguna"?: string;
  "pk-bangtao"?: string;
  "pk-cherngtalay"?: string;
  "pk-surin"?: string;
  "pk-kamala"?: string;
  "pk-kalim"?: string;
  "pk-tritrang"?: string;
  "pk-patong"?: string;
  "pk-karon"?: string;
  "pk-kata"?: string;
  "pk-rawai"?: string;
  "pk-naiharn"?: string;
  "pk-saiyuan"?: string;
  "pk-chalong"?: string;
  "pk-chaofa"?: string;
  "pk-siray"?: string;
  "pk-town"?: string;
  "pk-aoyon"?: string;
  "pk-panwa"?: string;
  "nt-panwa-pier"?: string;
  "pk-kathu"?: string;
  "pk-khokkloi"?: string;
  "pk-natai"?: string;
  "nt-tublamu-pier"?: string;
  "kl-numkhem"?: string;
  "kl-bangsak"?: string;
  "kl-pakwip"?: string;
  "kl-pakarang"?: string;
  "kl-khukkhak"?: string;
  "kl-bangniang"?: string;
  "kl-nanglao"?: string;
  "kl-center"?: string;
  "kl-khaolak"?: string;
  "kl-merlin"?: string;
  "kl-poseidon"?: string;
  "kl-tublamuhotel"?: string;
}

/** Table `fleet_projects`. */
export interface FleetProject {
  id: string;
  no?: string;
  name?: string;
  boatId?: string;
  type?: string;
  vendor?: string;
  planFrom?: string;
  planTo?: string;
  actualFrom?: string;
  actualTo?: string;
  status?: string;
  plannedBudget?: number;
  notes?: string;
  createdAt?: string;
  createdBy?: string;
  originalPlanTo?: string;
  docs?: unknown;
  vendorVisits?: unknown;
  phase?: string;
  holdReason?: string;
  holdSince?: string;
  cancelReason?: string;
  cancelledOn?: string;
  log?: FleetProjectLog[];
  plan?: FleetProjectPlan[];
}

/** Table `fleet_projects__log`. */
export interface FleetProjectLog {
  date?: string;
  text?: string;
  by?: string;
}

/** Table `fleet_projects__plan`. */
export interface FleetProjectPlan {
  id?: string;
  text?: string;
  done?: boolean;
  addedAt?: string;
  doneDate?: string;
}

/** Table `sb_seat_locks`. */
export interface SbSeatLock {
  id: string;
  routeId?: string;
  date?: string;
  boatId?: string;
  holderType?: string;
  holderId?: string;
  qty?: number;
  used?: number;
  reason?: string;
  expiry?: string;
  status?: string;
  createdAt?: string;
  createdBy?: string;
  scope?: string;
  month?: string;
  monthFrom?: string;
  monthTo?: string;
  parentId?: string;
  subName?: string;
  releaseDaysBefore?: number;
  releaseTime?: string;
  log?: SbSeatLockLog[];
}

/** Table `sb_seat_locks__log`. */
export interface SbSeatLockLog {
  date?: string;
  type?: string;
  qty?: number;
  at?: string;
  by?: string;
  bookingId?: string;
  sub?: boolean;
  note?: string;
}

/** Table `sb_sales`. */
export interface SbSale {
  id: string;
  code?: string;
  name?: string;
  color?: string;
  email?: string;
  fullName?: string;
  designation?: string;
  tel?: string;
  signature?: string;
  targets?: unknown;
  followup?: unknown;
}

/** Table `sb_agents`. */
export interface SbAgent {
  id: string;
  code?: string;
  name?: string;
  market?: string;
  sub?: string;
  sales?: string;
  payType?: string;
  vatMode?: string;
  creditDays?: number;
  creditLimit?: number;
  creditBalance?: number;
  contact?: string;
  email?: string;
  phone?: string;
  note?: string;
  contractStatus?: string;
  contractVersion?: string;
  companyInfo?: {
    legalName?: string;
    tatLicense?: string;
    address?: string;
    tel?: string;
    hotline?: string;
    fax?: string;
    website?: string;
    taxId?: string;
  };
  agentSignatory?: {
    name?: string;
    designation?: string;
    tel?: string;
    signedDate?: string;
  };
  bookingChannel?: {
    method?: string;
    cutoff?: string;
    cancelPolicy?: string;
    email?: string;
    phone?: string;
  };
  contractStart?: string;
  contractEnd?: string;
  rateTypeId?: string;
  color?: string;
  contractTemplateId?: string;
  programs?: string[];
  programPeriods?: SbAgentProgramPeriod[];
  activity?: SbAgentActivity[];
  contractHistory?: SbAgentContractHistory[];
}

/** Table `sb_agents__programperiods`. */
export interface SbAgentProgramPeriod {
  routeId?: string;
  bookFrom?: string;
  bookTo?: string;
  travelFrom?: string;
  travelTo?: string;
  note?: string;
}

/** Table `sb_agents__activity`. */
export interface SbAgentActivity {
  at?: string;
  by?: string;
  kind?: string;
  text?: string;
}

/** Table `sb_agents__contracthistory`. */
export interface SbAgentContractHistory {
  version?: string;
  archivedAt?: string;
  contractStart?: string;
  contractEnd?: string;
  snapshot?: {
    agentSignatory?: {
      name?: string;
      designation?: string;
      tel?: string;
      signedDate?: string;
    };
    programPeriods?: unknown;
    addonServices?: unknown;
    prices?: unknown;
  };
}

/** Table `sb_bookings`. */
export interface SbBooking {
  id: string;
  schemaVer?: number;
  createdAt?: string;
  createdBy?: string;
  voucherRef?: string;
  agentId?: string;
  rateTypeRef?: string;
  leadPax?: string;
  leadNationality?: string;
  leadType?: string;
  leadFoc?: boolean;
  leadPhone?: string;
  leadEmail?: string;
  pickupAreaId?: string;
  pickupSelf?: boolean;
  pickupArea?: string;
  pickupZone?: string;
  hotelName?: string;
  roomNumber?: string;
  dropoffSame?: boolean;
  dropoffAreaId?: string;
  dropoffArea?: string;
  dropoffHotelName?: string;
  guides?: {
    english?: boolean;
    russian?: boolean;
    chinese?: boolean;
    otherLang?: string;
  };
  notes?: string;
  specialMeals?: {
    veg?: number;
    vegan?: number;
    halal?: number;
    allergies?: string;
    allergyList?: unknown;
  };
  largeLuggage?: number;
  cashOnTour?: {
    amount?: number;
    currency?: string;
    handling?: string;
    note?: string;
  };
  focApproval?: {
    count?: number;
    reason?: string;
    status?: string;
    requestedAt?: string;
    requestedBy?: string;
    approvedAt?: string;
    approvedBy?: string;
  };
  paymentSnapshot?: {
    method?: string;
    netDays?: number;
    source?: string;
    contractVersion?: string;
    paid?: number;
    paidStatus?: string;
    deposit?: number;
    balance?: number;
  };
  priceBreakdown?: {
    seat?: number;
    addOn?: number;
    focDiscount?: number;
    discount?: number;
    extra?: number;
    total?: number;
  };
  status?: string;
  total?: number;
  soldBy?: string;
  priceMode?: string;
  manualTotal?: number;
  purpose?: string;
  staffId?: string;
  staffPurpose?: string;
  note?: string;
  bookedAt?: string;
  bookingDate?: string;
  marketSnapshot?: {
    market?: string;
    sub?: string;
    agentId?: string;
    at?: string;
  };
  confirmedBy?: string;
  confirmedAt?: string;
  ops?: {
    boatId?: string;
    vanGroup?: number;
    vanSeq?: number;
    vanReturnId?: string;
    vanId?: string;
    returnSameVan?: boolean;
    pickupTimeFinal?: string;
    reconfirm?: unknown;
    vanSplits?: unknown;
    boatSplits?: unknown;
    vanCheckin?: unknown;
    pierCheckin?: unknown;
    pierNote?: unknown;
  };
  updatedAt?: string;
  updatedBy?: string;
  focReason?: string;
  invoiceId?: string;
  paymentStatus?: string;
  cancelledAt?: string;
  cancellation?: {
    category?: string;
    categoryLabel?: string;
    group?: string;
    note?: string;
    reason?: string;
    chargeType?: string;
    chargeAmount?: number;
    at?: string;
    by?: string;
  };
  cancelCategory?: string;
  cancelReason?: string;
  reschedule?: {
    fromDate?: string;
    toDate?: string;
    reason?: string;
    chargeType?: string;
    chargeAmount?: number;
    collect?: string;
    at?: string;
    by?: string;
  };
  rebook?: {
    from?: string;
    to?: string;
    reason?: string;
    at?: string;
  };
  approval?: {
    status?: string;
    reason?: string;
    targetStatus?: string;
    totOver?: number;
    requestedBy?: string;
    requestedAt?: string;
    approvedBy?: string;
    approvedAt?: string;
    note?: string;
    over?: unknown;
  };
  weatherResolve?: {
    event?: string;
    status?: string;
    notifiedAt?: string;
    outcome?: string;
    resolvedAt?: string;
    newDate?: string;
  };
  editLock?: {
    uid?: string;
    by?: string;
    at?: number;
  };
  docCheck?: unknown;
  attachments?: unknown;
  paymentSlips?: unknown;
  incomplete?: unknown;
  altPickups?: unknown;
  pierPayments?: unknown;
  b2cOverride?: unknown;
  passengers?: SbBookingPassenger[];
  trips?: SbBookingTrip[];
  addOns?: SbBookingAddOn[];
  history?: SbBookingHistory[];
  upgrades?: SbBookingUpgrade[];
  feeItems?: SbBookingFeeItem[];
  partialCancels?: SbBookingPartialCancel[];
  adjustments?: SbBookingAdjustment[];
  over?: SbBookingOver[];
}

/** Table `sb_bookings__passengers`. */
export interface SbBookingPassenger {
  name?: string;
  nationality?: string;
  type?: string;
  foc?: boolean;
}

/** Table `sb_bookings__trips`. */
export interface SbBookingTrip {
  routeId?: string;
  date?: string;
  zone?: string;
  pax?: {
    ad_fr?: number;
    chd_fr?: number;
    inf_fr?: number;
    foc_fr?: number;
    ad_th?: number;
    chd_th?: number;
    inf_th?: number;
    foc_th?: number;
    ad?: number;
    foc?: number;
  };
  pickupTime?: string;
  bookingMode?: string;
  charterBoatId?: string;
  charterPriceMode?: string;
  charterPriceManual?: number;
  charterPriceNote?: string;
  charterDisplacementAck?: boolean;
  ovn?: string;
  ovnReturnDate?: string;
  ovnCharge?: number;
  ovnLeg?: boolean;
  ovnOf?: string;
  seatSource?: {
    locked?: number;
    general?: number;
  };
  subtotal?: number;
  nat?: {
    ad?: number;
    chd?: number;
    inf?: number;
    foc?: number;
  };
  lockDrawSel?: unknown;
  lockDraws?: unknown;
  ops?: {
    boatId?: string;
    vanId?: string;
    vanReturnId?: string;
    returnSameVan?: boolean;
    vanGroup?: number;
    vanSeq?: number;
    pickupTimeFinal?: string;
    vanSplits?: unknown;
    boatSplits?: unknown;
    reconfirm?: unknown;
    vanCheckin?: unknown;
    pierCheckin?: unknown;
    pierNote?: unknown;
  };
  promoId?: string;
}

/** Table `sb_bookings__addons`. */
export interface SbBookingAddOn {
  type?: string;
  label?: string;
  amount?: number;
  qty?: number;
  note?: string;
  jAd?: number;
  jChd?: number;
}

/** Table `sb_bookings__history`. */
export interface SbBookingHistory {
  at?: string;
  kind?: string;
  text?: string;
  tag?: string;
  by?: string;
}

/** Table `sb_bookings__upgrades`. */
export interface SbBookingUpgrade {
  id?: string;
  label?: string;
  sellPrice?: number;
  toCompany?: number;
  commission?: number;
  collected?: boolean;
  note?: string;
  seller?: string;
  settle?: string;
  at?: string;
  method?: string;
  feePct?: number;
  fee?: number;
  customerPaid?: number;
  slips?: unknown;
}

/** Table `sb_bookings__feeitems`. */
export interface SbBookingFeeItem {
  type?: string;
  label?: string;
  amount?: number;
  at?: string;
}

/** Table `sb_bookings__partialcancels`. */
export interface SbBookingPartialCancel {
  date?: string;
  tripIdx?: number;
  paxRemoved?: {
    foc_th?: number;
    ad_fr?: number;
  };
  count?: number;
  category?: string;
  categoryLabel?: string;
  group?: string;
  note?: string;
  refundMode?: string;
  refund?: number;
  charged?: {
    count?: number;
    amount?: number;
  };
  waived?: {
    count?: number;
    amount?: number;
  };
  at?: string;
  by?: string;
}

/** Table `sb_bookings__adjustments`. */
export interface SbBookingAdjustment {
  kind?: string;
  mode?: string;
  value?: number;
  label?: string;
  note?: string;
}

/** Table `sb_bookings__over`. */
export interface SbBookingOver {
  routeId?: string;
  date?: string;
  name?: string;
  need?: number;
  capFree?: number;
  overBy?: number;
  licFree?: number;
}

/** Table `sb_nationalities`. */
export interface SbNationality {
  id: string;
  code?: string;
  name?: string;
  custom?: boolean;
}

/** Table `sb_invoices`. */
export interface SbInvoice {
  id: string;
  number?: string;
  agentId?: string;
  subtotal?: number;
  depositApplied?: number;
  total?: number;
  issuedAt?: string;
  dueAt?: string;
  status?: string;
  createdBy?: string;
  netAmount?: number;
  vatMode?: string;
  vatRate?: number;
  vatAmount?: number;
  feeType?: string;
  note?: string;
  bookingIds?: string[];
  lineItems?: SbInvoiceLineItem[];
}

/** Table `sb_invoices__lineitems`. */
export interface SbInvoiceLineItem {
  label?: string;
  amount?: number;
}

/** Table `sb_weather`. */
export interface SbWeather {
  id: string;
  routeId?: string;
  date?: string;
  reason?: string;
  at?: string;
  note?: string;
}

/** Table `sb_payments`. */
export interface SbPayment {
  id: string;
  invoiceId?: string;
  agentId?: string;
  amount?: number;
  method?: string;
  date?: string;
  type?: string;
  slips?: unknown;
}

/** Table `sb_markets`. */
export interface SbMarket {
  id: string;
  name?: string;
  color?: string;
  sort?: number;
  subs?: string[];
}

/** Table `sb_staff`. */
export interface SbStaff {
  id: string;
  code?: string;
  name?: string;
  dept?: string;
  active?: boolean;
  quota?: {
    "2026"?: number;
  };
}

/** Table `sb_vehicles`. */
export interface SbVehicle {
  id: string;
  name?: string;
  plate?: string;
  type?: string;
  capacity?: number;
  ownership?: string;
  costPerDay?: number | string;
  partnerName?: string;
  zoneBase?: string;
  active?: boolean;
  note?: string;
  color?: string;
  driver?: string;
  driverPhone?: string;
  dayZone?: {
    "2026-06-12"?: string;
  };
  log?: SbVehicleLog[];
  statusRanges?: SbVehicleStatusRange[];
  dayRoute?: Record<string, unknown>;
  dayStatus?: Record<string, unknown>;
}

/** Table `sb_vehicles__log`. */
export interface SbVehicleLog {
  at?: string;
  kind?: string;
  text?: string;
}

/** Table `sb_vehicles__statusranges`. */
export interface SbVehicleStatusRange {
  s?: string;
  from?: string;
  to?: string;
  note?: string;
}

/** Table `sb_extras`. */
export interface SbExtra {
  id: string;
  bookingId?: string;
  tripDate?: string;
  service?: string;
  qty?: number;
  unitPrice?: number;
  total?: number;
  toCompany?: number;
  commission?: number;
  seller?: string;
  method?: string;
  settle?: string;
  date?: string;
  feePct?: number;
  fee?: number;
  customerPaid?: number;
  slips?: unknown;
}

/** Table `vanjob_driver`. */
export interface VanjobDriver {
  driver?: string;
  phone?: string;
  plate?: string;
}

/** Table `fleet_consumable_logs`. */
export interface FleetConsumableLog {
  id: string;
  date?: string;
  itemId?: string;
  itemName?: string;
  unit?: string;
  qty?: number;
  unitCost?: number;
  cost?: number;
  location?: string;
  boatId?: string;
  engineId?: string;
  engineLabel?: string;
  by?: string;
  note?: string;
}

/** Table `sb_contracts`. */
export interface SbContract {
  id: string;
  agentId?: string;
  kind?: string;
  rateTypeId?: string;
  activeFrom?: string;
  activeTo?: string;
  priority?: number;
  version?: string;
  status?: string;
  createdDate?: string;
  createdBy?: string;
  note?: string;
  docId?: string;
  priceMode?: string;
  rates?: unknown;
  discount?: unknown;
  bonus?: unknown;
  bookWin?: number;
  programPeriods?: SbContractProgramPeriod[];
}

/** Table `sb_contracts__programperiods`. */
export interface SbContractProgramPeriod {
  routeId?: string;
  bookFrom?: string;
  bookTo?: string;
  travelFrom?: string;
  travelTo?: string;
  note?: string;
}

/** Table `boat_capovr`. */
export interface BoatCapovr {
  cap?: number;
  reason?: string;
  by?: string;
  at?: string;
}

/** Table `travel_sum`. */
export interface TravelSum {
  decision?: string;
  amount?: number;
  note?: string;
  by?: string;
  at?: string;
}

/** Table `ts_cot`. */
export interface TsCot {
  mode?: string;
  deduct?: number;
  payout?: number;
  ref?: string;
  slips?: unknown;
  by?: string;
  at?: string;
}

/** Table `pier_items`. */
export interface PierItem {
  id: string;
  pier?: string;
  kind?: string;
  label?: string;
  total?: number;
  active?: boolean;
  note?: string;
}

/** Table `pier_kinds`. */
export interface PierKind {
  id: string;
  name?: string;
  name_en?: string;
  unit?: string;
  color?: string;
  ord?: number;
  active?: boolean;
}

/** Table `meal_venues`. */
export interface MealVenue {
  id: string;
  name?: string;
  place?: string;
  priceAd?: number | string;
  priceCh?: number | string;
  phone?: string;
  eta?: string;
  note?: string;
  active?: boolean;
}

/** Table `pier_moves`. */
export interface PierMove {
  id: string;
  date?: string;
  pier?: string;
  itemId?: string;
  boatId?: string;
  type?: string;
  qty?: number;
  from?: string;
  fine?: number;
  finePaid?: boolean;
  note?: string;
  by?: string;
  at?: string;
}

/** Table `pier_staff`. */
export interface PierStaff {
  id: string;
  pier?: string;
  nick?: string;
  name?: string;
  role?: string;
  phone?: string;
  active?: boolean;
  defCode?: string;
  sect?: string;
  note?: string;
  ord?: number;
}

/** Table `pier_sect`. */
export interface PierSect {
  id: string;
  pier?: string;
  name?: string;
  ord?: number;
}

/** Table `pier_lic_types`. */
export interface PierLicType {
  id: string;
  side?: string;
  short?: string;
  formal?: string;
  perBoat?: number;
  active?: boolean;
}

/** Table `pier_lic_classes`. */
export interface PierLicClass {
  id: string;
  typeId?: string;
  name?: string;
  maxGt?: number;
  maxBhp?: number;
  ord?: number;
}

/** Table `pier_licenses`. */
export interface PierLicense {
  id: string;
  staffId?: string;
  classId?: string;
  no?: string;
  exp?: string;
  issuedAt?: string;
  issuer?: string;
  note?: string;
}

/** Table `pier_codes`. */
export interface PierCode {
  id: string;
  code?: string;
  label?: string;
  color?: string;
  bg?: string;
  kind?: string;
  ord?: number;
  active?: boolean;
}

/** Table `po_cash_rows`. */
export interface PoCashRow {
  id: string;
  pier?: string;
  date?: string;
  kind?: string;
  txt?: string;
  amt?: number;
  at?: string;
  by?: string;
  ts?: string;
  src?: string;
}

/** Table `po_cash_lt`. */
export interface PoCashLt {
  id: string;
  pier?: string;
  date?: string;
  bid?: string;
  n?: number;
  nj?: number;
  nc?: number;
  amt?: number;
  note?: string;
  by?: string;
  ts?: string;
}

/** Table `po_cash_pk`. */
export interface PoCashPk {
  id: string;
  pier?: string;
  date?: string;
  bid?: string;
  ad_th?: number;
  chd_th?: number;
  inf_th?: number;
  foc_th?: number;
  ad_fr?: number;
  chd_fr?: number;
  inf_fr?: number;
  foc_fr?: number;
  amt?: number;
  dock?: number;
  by?: string;
  ts?: string;
  src?: string;
}

/**
 * The whole app state as /api/load returns it (the legacy `loveandaman_v2` blob). Top-level scalar
 * settings (table `app_meta`) sit beside these keys and are not listed here.
 */
export interface AppData {
  routes?: Route[];
  boats?: Boat[];
  trips?: TripDeployments;
  fleet_engines?: FleetEngine[];
  fleet_gearboxes?: FleetGearbox[];
  fleet_propellers?: FleetPropeller[];
  fleet_daily?: FleetDailyLog;
  fleet_maintenance?: FleetMaintenance[];
  fleet_incidents?: FleetIncident[];
  fleet_inventory?: FleetInventory[];
  fleet_memos?: FleetMemo[];
  _app_hooks?: Record<string, boolean>;
  sb_rate_types?: SbRateType[];
  sb_agents_rate_bindings?: SbAgentsRateBinding[];
  fleet_safety?: FleetSafety[];
  sb_pickup_areas?: SbPickupArea[];
  sb_pickup_times?: Record<string, SbPickupTime>;
  sb_pickup_time_profiles?: SbPickupTimeProfile[];
  fleet_projects?: FleetProject[];
  sb_seat_locks?: SbSeatLock[];
  sb_sales?: SbSale[];
  sb_agents?: SbAgent[];
  sb_bookings?: SbBooking[];
  nat_learn?: Record<string, unknown>;
  sb_nationalities?: SbNationality[];
  sb_invoices?: SbInvoice[];
  sb_weather?: SbWeather[];
  sb_payments?: SbPayment[];
  sb_markets?: SbMarket[];
  sb_market_stats?: Record<string, unknown>;
  sb_market_monthly?: Record<string, number>;
  sb_staff?: SbStaff[];
  sb_vehicles?: SbVehicle[];
  sb_extras?: SbExtra[];
  fleet_fuelprice?: Record<string, unknown>;
  fleet_drlock?: Record<string, unknown>;
  vanjob_pickup_th?: Record<string, string>;
  vanjob_driver?: Record<string, VanjobDriver>;
  fleet_consumable_logs?: FleetConsumableLog[];
  insurance_overrides?: Record<string, unknown>;
  vanjob_sreq?: Record<string, unknown>;
  vanjob_th_flag?: Record<string, unknown>;
  vanjob_sent?: Record<string, unknown>;
  agent_artifacts?: Record<string, unknown>;
  contract_templates?: Record<string, unknown>;
  sb_contracts?: SbContract[];
  boat_capovr?: Record<string, BoatCapovr>;
  travel_sum?: Record<string, TravelSum>;
  ts_cot?: Record<string, TsCot>;
  pier_items?: PierItem[];
  pier_kinds?: PierKind[];
  meal_venues?: MealVenue[];
  pier_moves?: PierMove[];
  pier_staff?: PierStaff[];
  pier_sect?: PierSect[];
  pier_duty?: Record<string, unknown>;
  pier_team?: Record<string, unknown>;
  pier_job?: Record<string, unknown>;
  trip_actuals?: Record<string, unknown>;
  pier_sheet?: Record<string, unknown>;
  pier_cfg?: Record<string, unknown>;
  pier_lic_types?: PierLicType[];
  pier_lic_classes?: PierLicClass[];
  pier_licenses?: PierLicense[];
  pier_codes?: PierCode[];
  pier_shift?: Record<string, unknown>;
  van_bill?: Record<string, unknown>;
  po_cash_rows?: PoCashRow[];
  po_cash_lt?: PoCashLt[];
  po_cash_pk?: PoCashPk[];
}
